import { useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ClipboardList, Copy, DatabaseBackup, FileText, Hash, Heart, Info, Link2, Mail, RefreshCw, Search, ShieldAlert, Smile, Sparkles, Star, UserCheck, Users } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../ui/button'; import { Input } from '../ui/input'; import { Label } from '../ui/label';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../ui/alert-dialog';
import { projectId } from '../../utils/supabase/info'; import { SecurityEmpty } from './AuditLog'; import '../../styles/security-console.css';
const BASE = `https://${projectId}.supabase.co/functions/v1/make-server-6d579fee`;
type Method = 'couple' | 'email' | 'audit' | 'uid'; type Step = 1 | 2 | 3;
interface RecoveryCandidate { userId: string; label: string; source: string; authExists: boolean; dataCounts: Record<string, number>; detail: string; }
const methods = [{ id:'couple' as const, icon:Link2, label:'Couple history', desc:'Find orphaned IDs through surviving relationship records.' },{ id:'email' as const, icon:Mail, label:'Email address', desc:'Locate old KV profiles associated with an email.' },{ id:'audit' as const, icon:ClipboardList, label:'Audit evidence', desc:'Recover identity from email or prayer history.' },{ id:'uid' as const, icon:Hash, label:'Known user ID', desc:'Continue directly when the previous ID is known.' }];
const dataIcons: Record<string, typeof Heart> = { prayers:Heart,journals:FileText,moods:Smile,milestones:Star,devotionalCompletions:BookOpen,questionResponses:Users,streaks:RefreshCw,scriptureMemory:BookOpen,notifications:Mail };

export function AccountRecovery({ accessToken }: { accessToken?: string }) {
  const [step,setStep]=useState<Step>(1); const [method,setMethod]=useState<Method>('couple'); const [oldUserId,setOldUserId]=useState(''); const [oldUserLabel,setOldUserLabel]=useState(''); const [newUserId,setNewUserId]=useState(''); const [searchEmail,setSearchEmail]=useState(''); const [auditEmail,setAuditEmail]=useState(''); const [prayerId,setPrayerId]=useState(''); const [knownId,setKnownId]=useState(''); const [results,setResults]=useState<RecoveryCandidate[]>([]); const [searching,setSearching]=useState(false); const [searched,setSearched]=useState(false); const [error,setError]=useState(''); const [migrating,setMigrating]=useState(false); const [migrationResult,setMigrationResult]=useState<Record<string, any>|null>(null); const [confirmOpen,setConfirmOpen]=useState(false);
  const headers={ 'Content-Type':'application/json',Authorization:`Bearer ${accessToken}` };
  const beginSearch=()=>{ setResults([]);setSearched(false);setError(''); if(method==='uid') return useKnownId(); void searchCandidates(); };
  async function searchCandidates(){ setSearching(true); try { let endpoint=''; let body:Record<string,string>={}; if(method==='couple'){endpoint='scan-couple-history';if(knownId.trim())body.targetUserId=knownId.trim();} else if(method==='email'){if(!searchEmail.trim())return;endpoint='find-orphaned-data';body.email=searchEmail.trim();} else {if(!auditEmail.trim()&&!prayerId.trim())return;endpoint='find-user-id-from-audit';if(auditEmail.trim())body.email=auditEmail.trim();if(prayerId.trim())body.prayerId=prayerId.trim();} const response=await fetch(`${BASE}/admin/${endpoint}`,{method:'POST',headers,body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');let found:RecoveryCandidate[]=[];if(method==='couple')found=[...(data.couples||[]).map((item:any)=>({userId:item.orphanedUserId,label:item.orphanedProfile?`${item.orphanedProfile.name} (${item.orphanedProfile.email})`:'Unknown profile',source:'Couple record',authExists:false,dataCounts:item.dataCounts||{},detail:`Partner: ${item.liveProfile?.name||'unknown'}`})),...(data.orphanedPartnerRefs||[]).map((item:any)=>({userId:item.orphanedUserId,label:`Partner of ${item.liveUser.name}`,source:'Partner reference',authExists:false,dataCounts:{},detail:`Referenced by ${item.liveUser.email}`}))];else if(method==='email')found=(data.accounts||[]).map((item:any)=>({userId:item.userId,label:`${item.name||'?'} — ${item.email}`,source:'KV profile',authExists:item.authExists,dataCounts:item.dataCounts||{},detail:`Created ${formatDate(item.createdAt)}${item.partnerName?` · Partner: ${item.partnerName}`:''}`}));else found=(data.results||[]).map((item:any)=>({userId:item.userId,label:`${item.userName||'?'} — ${item.userEmail}`,source:'Audit log',authExists:item.authExists,dataCounts:item.dataCounts||{},detail:`${item.auditEventCount} audit events · KV profile: ${item.hasKVProfile?'yes':'no'}`}));setResults(found);setSearched(true);if(!found.length)setError(data.message||'No recovery candidates found. Try another method.'); } catch(cause){setError(cause instanceof Error?cause.message:'Search failed');} finally{setSearching(false);} }
  async function useKnownId(){const uid=knownId.trim();if(!uid)return;setSearching(true);try{const response=await fetch(`${BASE}/admin/find-orphaned-data`,{method:'POST',headers,body:JSON.stringify({userId:uid})});let label=`User ID: ${uid}`;if(response.ok){const data=await response.json();const match=(data.accounts||[]).find((item:any)=>item.userId===uid);if(match)label=`${match.name||'?'} — ${match.email}`;}selectCandidate(uid,label);}finally{setSearching(false);} }
  function selectCandidate(id:string,label:string){setOldUserId(id);setOldUserLabel(label);setStep(2);window.scrollTo?.({top:0,behavior:'smooth'});}
  function requestMigration(){if(!oldUserId||!newUserId.trim())return;if(oldUserId===newUserId.trim()){toast.error('Source and destination IDs must be different');return;}setConfirmOpen(true);}
  async function runMigration(){setConfirmOpen(false);setMigrating(true);setMigrationResult(null);try{const response=await fetch(`${BASE}/admin/migrate-user-data`,{method:'POST',headers,body:JSON.stringify({fromUserId:oldUserId,toUserId:newUserId.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Migration failed');setMigrationResult(data);setStep(3);toast.success('Account recovery completed');}catch(cause){toast.error(cause instanceof Error?cause.message:'Migration failed');}finally{setMigrating(false);}}
  const reset=()=>{setStep(1);setOldUserId('');setOldUserLabel('');setNewUserId('');setResults([]);setSearched(false);setMigrationResult(null);setError('');};
  return <main className="recovery-console"><header className="security-hero"><div><span className="security-eyebrow"><Sparkles /> Guided data restoration</span><h1>Account Recovery</h1><p>Reconnect orphaned relationship data to a verified active account through a careful, auditable migration.</p></div><div className="security-hero__status"><span><DatabaseBackup /> KV data migration</span></div></header>
    <nav className="recovery-console__steps" aria-label="Recovery progress">{[{n:1,label:'Find source'},{n:2,label:'Review migration'},{n:3,label:'Complete'}].map((item,index)=><div key={item.n} data-active={step===item.n||undefined} data-complete={step>item.n||undefined}><span>{step>item.n?<CheckCircle2/>:item.n}</span><div><strong>{item.label}</strong><small>{index===0?'Locate old data':index===1?'Verify destination':'Review results'}</small></div>{index<2&&<i/>}</div>)}</nav>
    {step===1&&<section className="recovery-console__workspace"><aside className="recovery-console__methods" aria-label="Recovery search methods"><header><span>Discovery method</span><small>Choose the strongest evidence available</small></header>{methods.map(({id,icon:Icon,label,desc})=><button type="button" key={id} data-active={method===id||undefined} aria-pressed={method===id} onClick={()=>{setMethod(id);setResults([]);setSearched(false);setError('');}}><Icon/><div><strong>{label}</strong><small>{desc}</small></div><ArrowRight/></button>)}</aside><div className="recovery-console__search-panel"><div className="recovery-console__panel-heading"><Search/><div><h2>{methods.find((item)=>item.id===method)?.label}</h2><p>Search read-only evidence before selecting a source account.</p></div></div><div className="recovery-console__inputs">{method==='couple'&&<Field label="Known user ID (optional)" hint="Leave blank to scan all relationship records"><Input value={knownId} onChange={(e)=>setKnownId(e.target.value)} placeholder="Optional UUID" /></Field>}{method==='email'&&<Field label="Previous email address"><Input type="email" value={searchEmail} onChange={(e)=>setSearchEmail(e.target.value)} placeholder="person@example.com" /></Field>}{method==='audit'&&<><Field label="Email address"><Input type="email" value={auditEmail} onChange={(e)=>setAuditEmail(e.target.value)} placeholder="person@example.com" /></Field><Field label="Prayer ID (optional)"><Input value={prayerId} onChange={(e)=>setPrayerId(e.target.value)} placeholder="Content identifier" /></Field></>}{method==='uid'&&<Field label="Old user ID" hint="The deleted or replaced account whose data must be restored"><Input value={knownId} onChange={(e)=>setKnownId(e.target.value)} placeholder="Previous account UUID" /></Field>}<Button onClick={beginSearch} disabled={searching} className="recovery-console__primary">{searching?<RefreshCw className="security-spin"/>:<Search/>}{searching?'Searching…':method==='uid'?'Continue with this ID':'Search recovery evidence'}</Button></div>{error&&<div className="security-error" role="alert"><AlertTriangle/><div><strong>Recovery search needs attention</strong><p>{error}</p></div></div>}{searched&&results.length>0&&<div className="recovery-console__results"><header><span>{results.length} candidate{results.length===1?'':'s'} found</span><small>Verify the evidence before continuing</small></header>{results.map((item)=><Candidate key={`${item.source}-${item.userId}`} item={item} onSelect={()=>selectCandidate(item.userId,item.label)}/>)}</div>}{searched&&!results.length&&!error&&<SecurityEmpty icon={Search} title="No candidates found" message="Try another source of recovery evidence."/>}</div></section>}
    {step===2&&<section className="recovery-console__review"><div className="recovery-console__panel-heading"><UserCheck/><div><h2>Review the migration</h2><p>Confirm the old data source and active destination account.</p></div></div><div className="recovery-console__route"><AccountBox type="source" label="Old KV data" name={oldUserLabel} id={oldUserId}/><span><ArrowRight/></span><div className="recovery-console__destination"><label><Label htmlFor="recovery-new-id">Active destination user ID</Label><Input id="recovery-new-id" value={newUserId} onChange={(e)=>setNewUserId(e.target.value)} placeholder="New Supabase Auth UUID" /></label><small>The user must have logged into the new account at least once.</small></div></div><div className="recovery-console__migration-note"><Info/><div><strong>What this migration changes</strong><p>Copies prayers, journals, moods, milestones, completions, responses, streaks, memory, and notifications. It updates relationship links, then removes the old KV keys and profile. Supabase Auth accounts are not deleted.</p></div></div><footer><Button variant="outline" onClick={()=>setStep(1)}><ArrowLeft/> Back</Button><Button onClick={requestMigration} disabled={migrating||!newUserId.trim()||newUserId.trim()===oldUserId} className="recovery-console__primary">{migrating?<RefreshCw className="security-spin"/>:<DatabaseBackup/>} Review & migrate</Button></footer></section>}
    {step===3&&migrationResult&&<section className="recovery-console__complete"><span><CheckCircle2/></span><h2>Recovery complete</h2><p>The selected account data has been migrated to the active destination.</p><div className="recovery-console__complete-route"><AccountBox type="source" label="Previous ID" name={oldUserLabel} id={oldUserId}/><AccountBox type="destination" label="Active ID" name="Recovery destination" id={newUserId}/></div>{migrationResult.migrated&&<div className="recovery-console__counts">{Object.entries(migrationResult.migrated).filter(([key])=>key!=='oldProfileDeleted').map(([key,value])=>{const Icon=dataIcons[key]||Star;return <article key={key}><Icon/><strong>{String(value)}</strong><small>{key}</small></article>;})}</div>}<Button variant="outline" onClick={reset}>Start another recovery</Button></section>}
    <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent className="recovery-console__dialog max-w-[95vw] sm:max-w-xl"><AlertDialogHeader><div className="recovery-console__dialog-icon"><ShieldAlert/></div><AlertDialogTitle>Confirm irreversible KV migration</AlertDialogTitle><AlertDialogDescription asChild><div><p>Data will be copied to the active account, relationship references will be updated, and the old KV profile and source keys will be removed.</p><div className="recovery-console__dialog-route"><code>{oldUserId}</code><ArrowRight/><code>{newUserId.trim()}</code></div><p><strong>Supabase Auth accounts are not deleted.</strong> Confirm these IDs carefully before continuing.</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={migrating}>Cancel</AlertDialogCancel><AlertDialogAction onClick={runMigration} disabled={migrating} className="recovery-console__confirm">{migrating?'Migrating…':'Confirm migration'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="recovery-console__field"><Label>{label}</Label>{children}{hint&&<small>{hint}</small>}</label>}
function Candidate({item,onSelect}:{item:RecoveryCandidate;onSelect:()=>void}){return <article className="recovery-console__candidate"><header><span>{item.label.slice(0,1).toUpperCase()}</span><div><h3>{item.label}</h3><p>{item.source} · {item.detail}</p></div><i data-active={item.authExists||undefined}>{item.authExists?'Auth active':'Auth deleted'}</i></header><div className="recovery-console__data-badges">{Object.entries(item.dataCounts||{}).filter(([,count])=>count>0).map(([key,count])=>{const Icon=dataIcons[key]||Star;return <span key={key}><Icon/>{count} {key}</span>})}</div><div className="recovery-console__uid"><code>{item.userId}</code><button type="button" onClick={()=>{navigator.clipboard?.writeText(item.userId);toast.success('Copied user ID')}} aria-label={`Copy user ID ${item.userId}`}><Copy/></button></div><Button size="sm" onClick={onSelect}>Use this source account <ArrowRight/></Button></article>}
function AccountBox({type,label,name,id}:{type:'source'|'destination';label:string;name:string;id:string}){return <div className={`recovery-console__account recovery-console__account--${type}`}><span>{type==='source'?<DatabaseBackup/>:<UserCheck/>}</span><div><small>{label}</small><strong>{name}</strong><code>{id}</code></div></div>}
