import { formatUiDate } from '../../utils/uiDateTime';
import { LoadingMark } from '../BrandLoader';
import { useCurrentLanguage } from '../../utils/languageStore';
import { useUiCopy, UI_LOCALES } from "../../utils/uiTranslation";
import { adminSecurityMessages } from "../../locales/adminSecurity";
import { BackButton } from '../BackButton';
import { useState } from 'react';
import { AlertTriangle, ArrowRight, BookOpen, CheckCircle2, ClipboardList, Copy, DatabaseBackup, FileText, Hash, Heart, Info, Link2, Mail, RefreshCw, Search, ShieldAlert, Smile, Sparkles, Star, UserCheck, Users } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../ui/button'; import { Input } from '../ui/input'; import { Label } from '../ui/label';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../ui/alert-dialog';
import { projectId } from '../../utils/supabase/info'; import { SecurityEmpty } from './AuditLog'; import '../../styles/security-console.css';
const BASE = `https://${projectId}.supabase.co/functions/v1/make-server-6d579fee`;
type Method = 'couple' | 'email' | 'audit' | 'uid'; type Step = 1 | 2 | 3;
type RecoveryText = string | { source: string; params: Record<string, string | number> };
interface RecoveryCandidate { userId: string; label: RecoveryText; source: string; authExists: boolean; dataCounts: Record<string, number>; detail: RecoveryText; }
function recoveryText(value: RecoveryText, tr: ReturnType<typeof useUiCopy>, language: keyof typeof UI_LOCALES) { if (typeof value === 'string') return value; const params = { ...value.params }; if (typeof params.date === 'string') params.date = formatUiDate(new Date(params.date), UI_LOCALES[language]); if (typeof params.status === 'string') params.status = tr(params.status); return tr(value.source, params); }
const methods = [{ id:'couple' as const, icon:Link2, label:'Couple history', desc:'Find orphaned IDs through surviving relationship records.' },{ id:'email' as const, icon:Mail, label:'Email address', desc:'Locate old KV profiles associated with an email.' },{ id:'audit' as const, icon:ClipboardList, label:'Audit evidence', desc:'Recover identity from email or prayer history.' },{ id:'uid' as const, icon:Hash, label:'Known user ID', desc:'Continue directly when the previous ID is known.' }];
const dataIcons: Record<string, typeof Heart> = { prayers:Heart,journals:FileText,moods:Smile,milestones:Star,devotionalCompletions:BookOpen,questionResponses:Users,streaks:RefreshCw,scriptureMemory:BookOpen,notifications:Mail };

export function AccountRecovery({ accessToken }: { accessToken?: string }) {
  const language = useCurrentLanguage();
  const tr = useUiCopy(adminSecurityMessages);
  const [step,setStep]=useState<Step>(1); const [method,setMethod]=useState<Method>('couple'); const [oldUserId,setOldUserId]=useState(''); const [oldUserLabel,setOldUserLabel]=useState<RecoveryText>(''); const [newUserId,setNewUserId]=useState(''); const [searchEmail,setSearchEmail]=useState(''); const [auditEmail,setAuditEmail]=useState(''); const [prayerId,setPrayerId]=useState(''); const [knownId,setKnownId]=useState(''); const [results,setResults]=useState<RecoveryCandidate[]>([]); const [searching,setSearching]=useState(false); const [searched,setSearched]=useState(false); const [error,setError]=useState(''); const [migrating,setMigrating]=useState(false); const [migrationResult,setMigrationResult]=useState<Record<string, any>|null>(null); const [confirmOpen,setConfirmOpen]=useState(false);
  const headers={ 'Content-Type':'application/json',Authorization:`Bearer ${accessToken}` };
  const beginSearch=()=>{ setResults([]);setSearched(false);setError(''); if(method==='uid') return useKnownId(); void searchCandidates(); };
  async function searchCandidates(){ setSearching(true); try { let endpoint=''; let body:Record<string,string>={}; if(method==='couple'){endpoint='scan-couple-history';if(knownId.trim())body.targetUserId=knownId.trim();} else if(method==='email'){if(!searchEmail.trim())return;endpoint='find-orphaned-data';body.email=searchEmail.trim();} else {if(!auditEmail.trim()&&!prayerId.trim())return;endpoint='find-user-id-from-audit';if(auditEmail.trim())body.email=auditEmail.trim();if(prayerId.trim())body.prayerId=prayerId.trim();} const response=await fetch(`${BASE}/admin/${endpoint}`,{method:'POST',headers,body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');let found:RecoveryCandidate[]=[];if(method==='couple')found=[...(data.couples||[]).map((item:any)=>({userId:item.orphanedUserId,label:item.orphanedProfile?`${item.orphanedProfile.name} (${item.orphanedProfile.email})`:{source:'Unknown profile',params:{}},source:'Couple record',authExists:false,dataCounts:item.dataCounts||{},detail:{source:'Partner: {name}',params:{name:item.liveProfile?.name||'?'}}})),...(data.orphanedPartnerRefs||[]).map((item:any)=>({userId:item.orphanedUserId,label:{source:'Partner of {name}',params:{name:item.liveUser.name}},source:'Partner reference',authExists:false,dataCounts:{},detail:{source:'Referenced by {email}',params:{email:item.liveUser.email}}}))];else if(method==='email')found=(data.accounts||[]).map((item:any)=>({userId:item.userId,label:`${item.name||'?'} — ${item.email}`,source:'KV profile',authExists:item.authExists,dataCounts:item.dataCounts||{},detail:{source:item.partnerName?'Created {date} · Partner: {name}':'Created {date}',params:{date:item.createdAt,name:item.partnerName||''}}}));else found=(data.results||[]).map((item:any)=>({userId:item.userId,label:`${item.userName||'?'} — ${item.userEmail}`,source:'Audit log',authExists:item.authExists,dataCounts:item.dataCounts||{},detail:{source:'{count} audit events · KV profile: {status}',params:{count:item.auditEventCount,status:item.hasKVProfile?'Yes':'No'}}}));setResults(found);setSearched(true);if(!found.length)setError(data.message||'No recovery candidates found. Try another method.'); } catch(cause){setError(cause instanceof Error?cause.message:'Search failed');} finally{setSearching(false);} }
  async function useKnownId(){const uid=knownId.trim();if(!uid)return;setSearching(true);try{const response=await fetch(`${BASE}/admin/find-orphaned-data`,{method:'POST',headers,body:JSON.stringify({userId:uid})});let label: RecoveryText={source:'User ID: {id}',params:{id:uid}};if(response.ok){const data=await response.json();const match=(data.accounts||[]).find((item:any)=>item.userId===uid);if(match)label=`${match.name||'?'} — ${match.email}`;}selectCandidate(uid,label);}finally{setSearching(false);} }
  function selectCandidate(id:string,label:RecoveryText){setOldUserId(id);setOldUserLabel(label);setStep(2);window.scrollTo?.({top:0,behavior:'smooth'});}
  function requestMigration(){if(!oldUserId||!newUserId.trim())return;if(oldUserId===newUserId.trim()){toast.error(tr("Source and destination IDs must be different"));return;}setConfirmOpen(true);}
  async function runMigration(){setConfirmOpen(false);setMigrating(true);setMigrationResult(null);try{const response=await fetch(`${BASE}/admin/migrate-user-data`,{method:'POST',headers,body:JSON.stringify({fromUserId:oldUserId,toUserId:newUserId.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Migration failed');setMigrationResult(data);setStep(3);toast.success(tr("Account recovery completed"));}catch(cause){toast.error(tr('Migration failed'));}finally{setMigrating(false);}}
  const reset=()=>{setStep(1);setOldUserId('');setOldUserLabel('');setNewUserId('');setResults([]);setSearched(false);setMigrationResult(null);setError('');};
  return <main className="recovery-console"><header className="security-hero"><div><span className="security-eyebrow"><Sparkles /> {tr("Guided data restoration")}</span><h1>{tr("Account Recovery")}</h1><p>{tr("Reconnect orphaned relationship data to a verified active account through a careful, auditable migration.")}</p></div><div className="security-hero__status"><span><DatabaseBackup /> {tr("KV data migration")}</span></div></header>
    <nav className="recovery-console__steps" aria-label={tr("Recovery progress")}>{[{n:1,label:'Find source'},{n:2,label:'Review migration'},{n:3,label:'Complete'}].map((item,index)=><div key={item.n} data-active={step===item.n||undefined} data-complete={step>item.n||undefined}><span>{step>item.n?<CheckCircle2/>:item.n}</span><div><strong>{tr(item.label)}</strong><small>{index===0?tr("Locate old data"):index===1?tr("Verify destination"):tr("Review results")}</small></div>{index<2&&<i/>}</div>)}</nav>
    {step===1&&<section className="recovery-console__workspace"><aside className="recovery-console__methods" aria-label={tr("Recovery search methods")}><header><span>{tr("Discovery method")}</span><small>{tr("Choose the strongest evidence available")}</small></header>{methods.map(({id,icon:Icon,label,desc})=><button type="button" key={id} data-active={method===id||undefined} aria-pressed={method===id} onClick={()=>{setMethod(id);setResults([]);setSearched(false);setError('');}}><Icon/><div><strong>{tr(label)}</strong><small>{tr(desc)}</small></div><ArrowRight/></button>)}</aside><div className="recovery-console__search-panel"><div className="recovery-console__panel-heading"><Search/><div><h2>{tr(methods.find((item)=>item.id===method)?.label || '')}</h2><p>{tr("Search read-only evidence before selecting a source account.")}</p></div></div><div className="recovery-console__inputs">{method==='couple'&&<Field label={tr("Known user ID (optional)")} hint="Leave blank to scan all relationship records"><Input value={knownId} onChange={(e)=>setKnownId(e.target.value)} placeholder={tr("Optional UUID")} /></Field>}{method==='email'&&<Field label={tr("Previous email address")}><Input type="email" value={searchEmail} onChange={(e)=>setSearchEmail(e.target.value)} placeholder="person@example.com" /></Field>}{method==='audit'&&<><Field label={tr("Email address")}><Input type="email" value={auditEmail} onChange={(e)=>setAuditEmail(e.target.value)} placeholder="person@example.com" /></Field><Field label={tr("Prayer ID (optional)")}><Input value={prayerId} onChange={(e)=>setPrayerId(e.target.value)} placeholder={tr("Content identifier")} /></Field></>}{method==='uid'&&<Field label={tr("Old user ID")} hint="The deleted or replaced account whose data must be restored"><Input value={knownId} onChange={(e)=>setKnownId(e.target.value)} placeholder={tr("Previous account UUID")} /></Field>}<Button onClick={beginSearch} disabled={searching} className="recovery-console__primary">{searching?<LoadingMark/>:<Search/>}{searching?tr("Searching…"):method==='uid'?tr("Continue with this ID"):tr("Search recovery evidence")}</Button></div>{error&&<div className="security-error" role="alert"><AlertTriangle/><div><strong>{tr("Recovery search needs attention")}</strong><p>{tr(error)}</p></div></div>}{searched&&results.length>0&&<div className="recovery-console__results"><header><span>{tr("{count} candidates found", { count: results.length })}</span><small>{tr("Verify the evidence before continuing")}</small></header>{results.map((item)=><Candidate key={`${item.source}-${item.userId}`} item={item} onSelect={()=>selectCandidate(item.userId,item.label)}/>)}</div>}{searched&&!results.length&&!error&&<SecurityEmpty icon={Search} title={tr("No candidates found")} message={tr("Try another source of recovery evidence.")}/>}</div></section>}
    {step===2&&<section className="recovery-console__review"><div className="recovery-console__panel-heading"><UserCheck/><div><h2>{tr("Review the migration")}</h2><p>{tr("Confirm the old data source and active destination account.")}</p></div></div><div className="recovery-console__route"><AccountBox type="source" label={tr("Old KV data")} name={recoveryText(oldUserLabel,tr,language)} id={oldUserId}/><span><ArrowRight/></span><div className="recovery-console__destination"><label><Label htmlFor="recovery-new-id">{tr("Active destination user ID")}</Label><Input id="recovery-new-id" value={newUserId} onChange={(e)=>setNewUserId(e.target.value)} placeholder={tr("New Supabase Auth UUID")} /></label><small>{tr("The user must have logged into the new account at least once.")}</small></div></div><div className="recovery-console__migration-note"><Info/><div><strong>{tr("What this migration changes")}</strong><p>{tr("Copies prayers, journals, moods, milestones, completions, responses, streaks, memory, and notifications. It updates relationship links, then removes the old KV keys and profile. Supabase Auth accounts are not deleted.")}</p></div></div><footer><BackButton onClick={()=>setStep(1)} label={tr("Back")} showLabel /><Button onClick={requestMigration} disabled={migrating||!newUserId.trim()||newUserId.trim()===oldUserId} className="recovery-console__primary">{migrating?<LoadingMark/>:<DatabaseBackup/>} {tr("Review & migrate")}</Button></footer></section>}
    {step===3&&migrationResult&&<section className="recovery-console__complete"><span><CheckCircle2/></span><h2>{tr("Recovery complete")}</h2><p>{tr("The selected account data has been migrated to the active destination.")}</p><div className="recovery-console__complete-route"><AccountBox type="source" label={tr("Previous ID")} name={recoveryText(oldUserLabel,tr,language)} id={oldUserId}/><AccountBox type="destination" label={tr("Active ID")} name={tr("Recovery destination")} id={newUserId}/></div>{migrationResult.migrated&&<div className="recovery-console__counts">{Object.entries(migrationResult.migrated).filter(([key])=>key!=='oldProfileDeleted').map(([key,value])=>{const Icon=dataIcons[key]||Star;return <article key={key}><Icon/><strong>{String(value)}</strong><small>{tr(key)}</small></article>;})}</div>}<Button variant="outline" onClick={reset}>{tr("Start another recovery")}</Button></section>}
    <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent className="recovery-console__dialog max-w-[95vw] sm:max-w-xl"><AlertDialogHeader><div className="recovery-console__dialog-icon"><ShieldAlert/></div><AlertDialogTitle>{tr("Confirm irreversible KV migration")}</AlertDialogTitle><AlertDialogDescription asChild><div><p>{tr("Data will be copied to the active account, relationship references will be updated, and the old KV profile and source keys will be removed.")}</p><div className="recovery-console__dialog-route"><code>{oldUserId}</code><ArrowRight/><code>{newUserId.trim()}</code></div><p><strong>{tr("Supabase Auth accounts are not deleted.")}</strong> {tr("Confirm these IDs carefully before continuing.")}</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={migrating}>{tr("Cancel")}</AlertDialogCancel><AlertDialogAction onClick={runMigration} disabled={migrating} className="recovery-console__confirm">{migrating?tr("Migrating…"):tr("Confirm migration")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){const tr = useUiCopy(adminSecurityMessages);return <label className="recovery-console__field"><Label>{tr(label)}</Label>{children}{hint&&<small>{tr(hint)}</small>}</label>}
function Candidate({item,onSelect}:{item:RecoveryCandidate;onSelect:()=>void}){
  const tr = useUiCopy(adminSecurityMessages); const language = useCurrentLanguage(); const label = recoveryText(item.label,tr,language); return <article className="recovery-console__candidate"><header><span>{label.slice(0,1).toUpperCase()}</span><div><h3>{label}</h3><p>{tr(item.source)} · {recoveryText(item.detail,tr,language)}</p></div><i data-active={item.authExists||undefined}>{item.authExists?tr("Auth active"):tr("Auth deleted")}</i></header><div className="recovery-console__data-badges">{Object.entries(item.dataCounts||{}).filter(([,count])=>count>0).map(([key,count])=>{const Icon=dataIcons[key]||Star;return <span key={key}><Icon/>{count} {tr(key)}</span>})}</div><div className="recovery-console__uid"><code>{item.userId}</code><button type="button" onClick={()=>{navigator.clipboard?.writeText(item.userId);toast.success(tr("Copied user ID"))}} aria-label={tr('Copy user ID {id}', { id: item.userId })}><Copy/></button></div><Button size="sm" onClick={onSelect}>{tr("Use this source account")}<ArrowRight/></Button></article>}
function AccountBox({type,label,name,id}:{type:'source'|'destination';label:string;name:string;id:string}){return <div className={`recovery-console__account recovery-console__account--${type}`}><span>{type==='source'?<DatabaseBackup/>:<UserCheck/>}</span><div><small>{label}</small><strong>{name}</strong><code>{id}</code></div></div>}
