import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, ArrowLeft, ArrowRight, BookOpen, ChevronRight, Clock3, Eye, FileJson, Filter, Heart, RefreshCw, Search, Shield, ShieldAlert, Sparkles, UserRound, Users, X } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { projectId } from '../../utils/supabase/info';
import '../../styles/security-console.css';

export interface AuditEntry { id: string; event: string; category: string; userId: string; userName: string; userEmail: string; metadata: Record<string, unknown>; timestamp: string; }
interface AuditLogProps { accessToken: string; }
const PAGE_SIZE = 25;
const BASE = `https://${projectId}.supabase.co/functions/v1/make-server-6d579fee`;
const ALL_EVENTS = ['user.signup','user.email_verified','couple.linked','couple.unlinked','devotional.completed','prayer.created','prayer.answered','journal.created','qa.answered','mood.logged','profile.updated','admin.privilege_granted','admin.privilege_revoked','admin.devotional_created','admin.devotional_updated','admin.devotional_deleted','admin.question_created','admin.question_updated','admin.question_deleted','admin.module_created','admin.module_updated','admin.module_deleted','admin.group_created','admin.group_updated','admin.group_deleted','admin.user_deleted','admin.landing_page_updated','admin.account_recovery_migration'];

export function AuditLog({ accessToken }: AuditLogProps) {
  const [entries, setEntries] = useState<AuditEntry[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [page, setPage] = useState(0);
  const [category, setCategory] = useState(''); const [event, setEvent] = useState(''); const [userId, setUserId] = useState(''); const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const fetchLog = useCallback(async (nextPage = 0) => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: String(PAGE_SIZE), offset: String(nextPage * PAGE_SIZE) }); if (category) params.set('category', category); if (event) params.set('event', event); if (userId.trim()) params.set('userId', userId.trim()); const response = await fetch(`${BASE}/admin/audit-log?${params}`, { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); const nextEntries = Array.isArray(data.entries) ? data.entries : []; setEntries(nextEntries); setTotal(Number(data.total || 0)); setPage(nextPage); setSelectedId((current) => current && nextEntries.some((item: AuditEntry) => item.id === current) ? current : nextEntries[0]?.id || null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not reach the audit service'); } finally { setLoading(false); } }, [accessToken, category, event, userId]);
  useEffect(() => { void fetchLog(0); }, [fetchLog]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return !query ? entries : entries.filter((entry) => [entry.event, entry.userName, entry.userEmail, JSON.stringify(entry.metadata)].some((value) => value?.toLowerCase().includes(query))); }, [entries, search]);
  const selected = filtered.find((entry) => entry.id === selectedId) || filtered[0] || null;
  const adminEvents = entries.filter((entry) => entry.category === 'admin').length; const uniqueActors = new Set(entries.map((entry) => entry.userId).filter(Boolean)).size; const today = entries.filter((entry) => new Date(entry.timestamp).toDateString() === new Date().toDateString()).length; const pages = Math.ceil(total / PAGE_SIZE);
  return <main className="audit-console">
    <header className="security-hero"><div><span className="security-eyebrow"><Sparkles /> Security intelligence</span><h1>Audit Log</h1><p>Investigate system activity with a durable, database-backed record of user and administrator actions.</p></div><div className="security-hero__status"><span><Shield /> Append-only activity view</span><Button variant="outline" onClick={() => fetchLog(page)} disabled={loading} aria-label="Refresh audit log"><RefreshCw className={loading ? 'security-spin' : ''} /> Refresh</Button></div></header>
    <section className="security-metrics" aria-label="Audit activity summary"><article><span><Activity /></span><div><strong>{total}</strong><small>Matching events</small></div></article><article><span><ShieldAlert /></span><div><strong>{adminEvents}</strong><small>Admin events on page</small></div></article><article><span><Users /></span><div><strong>{uniqueActors}</strong><small>Unique actors on page</small></div></article><article><span><Clock3 /></span><div><strong>{today}</strong><small>Events today</small></div></article></section>
    <section className="audit-console__toolbar" aria-label="Audit log filters"><div className="security-search"><Search /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search actor, event, or metadata…" aria-label="Search audit events" />{search && <button type="button" onClick={() => setSearch('')} aria-label="Clear audit search"><X /></button>}</div><label><Filter /><select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter audit category"><option value="">All categories</option><option value="auth">Authentication</option><option value="social">Social</option><option value="content">Content</option><option value="admin">Administration</option></select></label><label><Activity /><select value={event} onChange={(e) => setEvent(e.target.value)} aria-label="Filter audit event"><option value="">All events</option>{ALL_EVENTS.map((item) => <option key={item}>{item}</option>)}</select></label><Input value={userId} onChange={(e) => setUserId(e.target.value)} placeholder="Exact user ID" aria-label="Filter audit log by exact user ID" /></section>
    {error && <section className="security-error" role="alert"><AlertCircle /><div><strong>Could not load the audit log</strong><p>{error}</p></div><button type="button" onClick={() => fetchLog(0)}>Retry</button></section>}
    <div className="audit-console__result-line" role="status"><span>{filtered.length} events on this page</span>{(search || category || event || userId) && <button type="button" onClick={() => { setSearch(''); setCategory(''); setEvent(''); setUserId(''); }}>Clear filters</button>}</div>
    <section className="audit-console__workspace"><div className="audit-console__timeline" aria-label="Audit event timeline" aria-busy={loading}>{loading && [...Array(6)].map((_, index) => <div className="security-skeleton" key={index} />)}{!loading && filtered.map((entry) => <article key={entry.id} data-active={(selectedId ? selectedId === entry.id : selected?.id === entry.id) || undefined}><button type="button" onClick={() => setSelectedId(entry.id)} aria-label={`Inspect ${entry.event} by ${entry.userName || entry.userEmail || 'unknown actor'}`}><span className={`audit-console__event-icon audit-console__event-icon--${entry.category}`}>{eventIcon(entry)}</span><div><div><h2>{humanEvent(entry.event)}</h2><span className={`audit-console__category audit-console__category--${entry.category}`}>{entry.category}</span></div><p>{entry.userName || 'Unknown actor'} <small>{entry.userEmail}</small></p><time dateTime={entry.timestamp}>{new Date(entry.timestamp).toLocaleString()}</time></div><ChevronRight /></button></article>)}{!loading && !filtered.length && <SecurityEmpty icon={Shield} title="No audit events found" message="Adjust the filters or wait for new system activity." />}</div><AuditPreview entry={selected} /></section>
    {pages > 1 && <nav className="audit-console__pagination" aria-label="Audit log pages"><span>Page {page + 1} of {pages} · {total} total</span><div><Button variant="outline" size="icon" onClick={() => fetchLog(page - 1)} disabled={page === 0 || loading} aria-label="Previous audit page"><ArrowLeft /></Button><Button variant="outline" size="icon" onClick={() => fetchLog(page + 1)} disabled={page >= pages - 1 || loading} aria-label="Next audit page"><ArrowRight /></Button></div></nav>}
  </main>;
}
function eventIcon(entry: AuditEntry) { if (entry.category === 'admin') return <ShieldAlert />; if (entry.event.includes('prayer')) return <Heart />; if (entry.event.includes('devotional') || entry.event.includes('journal')) return <BookOpen />; return <UserRound />; }
function humanEvent(value: string) { return value.split('.').map((part) => part.replaceAll('_', ' ')).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' · '); }
function AuditPreview({ entry }: { entry: AuditEntry | null }) { if (!entry) return <aside className="audit-console__preview"><SecurityEmpty icon={Eye} title="Select an event" message="Actor, timestamp, identifiers, and metadata will appear here." /></aside>; return <aside className="audit-console__preview" aria-label="Selected audit event"><header><span className={`audit-console__event-icon audit-console__event-icon--${entry.category}`}>{eventIcon(entry)}</span><div><span className={`audit-console__category audit-console__category--${entry.category}`}>{entry.category}</span><h2>{humanEvent(entry.event)}</h2><code>{entry.event}</code></div></header><dl><div><dt>Actor</dt><dd>{entry.userName || 'Unknown'}</dd></div><div><dt>Email</dt><dd>{entry.userEmail || 'Not recorded'}</dd></div><div><dt>User ID</dt><dd><code>{entry.userId || 'Not recorded'}</code></dd></div><div><dt>Timestamp</dt><dd>{new Date(entry.timestamp).toLocaleString()}</dd></div><div><dt>Event ID</dt><dd><code>{entry.id}</code></dd></div></dl><section><div><FileJson /><span><strong>Event metadata</strong><small>{Object.keys(entry.metadata || {}).length} fields</small></span></div>{Object.keys(entry.metadata || {}).length ? <pre>{JSON.stringify(entry.metadata, null, 2)}</pre> : <p>No additional metadata was recorded.</p>}</section><footer><Shield /><span>This record is read-only and cannot be changed from the console.</span></footer></aside>; }
export function SecurityEmpty({ icon: Icon, title, message }: { icon: typeof Eye; title: string; message: string }) { return <div className="security-empty"><Icon /><h2>{title}</h2><p>{message}</p></div>; }
