import { Activity, ArrowUpDown, CalendarDays, ChevronRight, Clock3, Eye, FileHeart, Heart, HeartHandshake, Mail, MessageSquareText, RefreshCw, Search, ShieldCheck, Sparkles, Trash2, UserRound, Users, X } from 'lucide-react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../ui/alert-dialog';
import type { Couple, User } from '../UsersManager';

interface Props {
  users: User[]; filteredUsers: User[]; couples: Couple[]; filteredCouples: Couple[]; selectedUser: User | null;
  selectedId: string | null; isLoading: boolean; searchQuery: string; view: 'people' | 'couples';
  statusFilter: 'all' | User['status']; connectionFilter: 'all' | 'connected' | 'solo'; sortOrder: 'activity' | 'joined' | 'name';
  userToDelete: User | null; isDeleting: boolean; onSearchChange: (value: string) => void;
  onViewChange: (view: Props['view']) => void; onStatusFilterChange: (status: Props['statusFilter']) => void;
  onConnectionFilterChange: (status: Props['connectionFilter']) => void; onSortOrderChange: (sort: Props['sortOrder']) => void;
  onSelect: (id: string) => void; onRefresh: () => void; onDeleteRequest: (user: User) => void;
  onDeleteCancel: () => void; onDeleteConfirm: (id: string) => void;
}

const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const relativeActivity = (value: string) => { const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86_400_000)); return days === 0 ? 'Today' : days === 1 ? 'Yesterday' : `${days} days ago`; };
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export function UsersWorkspace(props: Props) {
  const { users, filteredUsers, couples, filteredCouples, selectedUser, selectedId, isLoading, searchQuery, view,
    statusFilter, connectionFilter, sortOrder, userToDelete, isDeleting, onSearchChange, onViewChange,
    onStatusFilterChange, onConnectionFilterChange, onSortOrderChange, onSelect, onRefresh,
    onDeleteRequest, onDeleteCancel, onDeleteConfirm } = props;
  const active = users.filter((user) => user.status === 'active').length;
  const journals = users.reduce((total, user) => total + user.journalEntries, 0);

  return <main className="user-console">
    <header className="user-console__hero"><div><span className="user-console__eyebrow"><Sparkles /> Account operations</span><h1>User Management</h1><p>Understand engagement, support connected couples, and manage member accounts with clarity and care.</p></div><div className="user-console__sync"><span><i className={isLoading ? 'user-console__pulse' : ''} /> {isLoading ? 'Syncing accounts' : 'Database connected'}</span><Button variant="outline" onClick={onRefresh} disabled={isLoading} aria-label="Refresh user accounts"><RefreshCw className={isLoading ? 'user-console__spin' : ''} /> Refresh</Button></div></header>

    <section className="user-console__metrics" aria-label="User account summary"><article><span><Users /></span><div><strong>{users.length}</strong><small>Total users</small></div></article><article><span><HeartHandshake /></span><div><strong>{couples.length}</strong><small>Connected couples</small></div></article><article><span><Activity /></span><div><strong>{active}</strong><small>Recently active</small></div></article><article><span><FileHeart /></span><div><strong>{journals}</strong><small>Journal entries</small></div></article></section>

    <section className="user-console__toolbar" aria-label="User directory controls"><div className="user-console__search"><Search /><Input value={searchQuery} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search name, email, or partner…" aria-label="Search users" />{searchQuery && <button type="button" onClick={() => onSearchChange('')} aria-label="Clear user search"><X /></button>}</div><div className="user-console__views" aria-label="Choose directory view"><button type="button" data-active={view === 'people' || undefined} aria-pressed={view === 'people'} onClick={() => onViewChange('people')}><UserRound /> People</button><button type="button" data-active={view === 'couples' || undefined} aria-pressed={view === 'couples'} onClick={() => onViewChange('couples')}><Heart /> Couples</button></div><label className="user-console__select"><Activity /><span className="sr-only">Activity</span><select value={statusFilter} onChange={(event) => onStatusFilterChange(event.target.value as Props['statusFilter'])} aria-label="Filter users by activity"><option value="all">All activity</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{view === 'people' && <label className="user-console__select"><Heart /><span className="sr-only">Connection</span><select value={connectionFilter} onChange={(event) => onConnectionFilterChange(event.target.value as Props['connectionFilter'])} aria-label="Filter users by connection"><option value="all">All connections</option><option value="connected">Connected</option><option value="solo">Solo</option></select></label>}<label className="user-console__select"><ArrowUpDown /><span className="sr-only">Sort</span><select value={sortOrder} onChange={(event) => onSortOrderChange(event.target.value as Props['sortOrder'])} aria-label="Sort users"><option value="activity">Recent activity</option><option value="joined">Recently joined</option><option value="name">Name A–Z</option></select></label></section>

    <div className="user-console__result-line" role="status"><span>{view === 'people' ? `${filteredUsers.length} people` : `${filteredCouples.length} couples`}</span>{(searchQuery || statusFilter !== 'all' || connectionFilter !== 'all') && <button type="button" onClick={() => { onSearchChange(''); onStatusFilterChange('all'); onConnectionFilterChange('all'); }}>Clear filters</button>}</div>

    {view === 'people' ? <section className="user-console__workspace"><div className="user-console__directory" aria-label="User directory" aria-busy={isLoading}>{isLoading && [...Array(5)].map((_, index) => <div className="user-console__skeleton" key={index} />)}{!isLoading && filteredUsers.map((user, index) => { const selected = selectedId ? user.id === selectedId : selectedUser?.id === user.id; return <article className="user-console__row" data-active={selected || undefined} key={user.id}><button className="user-console__row-main" type="button" onClick={() => onSelect(user.id)} aria-label={`View account for ${user.name}`}><span className={`user-console__avatar user-console__avatar--${index % 4}`}>{initials(user.name)}</span><div><div className="user-console__row-title"><h2>{user.name}</h2><span className={`user-console__status user-console__status--${user.status}`}>{user.status}</span></div><p><Mail /> {user.email}</p><small>{user.partnerId ? <span><Heart /> Connected to {user.partnerName || 'partner'}</span> : <span><UserRound /> Solo account</span>}<span><Clock3 /> {relativeActivity(user.lastActive)}</span></small></div><ChevronRight /></button></article>; })}{!isLoading && !filteredUsers.length && <Empty title="No users found" message="Adjust the filters to find another account." />}</div><UserPreview user={selectedUser} onDelete={onDeleteRequest} /></section> : <section className="user-console__couples" aria-label="Connected couples" aria-busy={isLoading}>{isLoading && [...Array(4)].map((_, index) => <div className="user-console__skeleton" key={index} />)}{!isLoading && filteredCouples.map((couple) => <CoupleCard key={couple.id} couple={couple} onSelect={(id) => { onSelect(id); onViewChange('people'); }} />)}{!isLoading && !filteredCouples.length && <Empty title="No couples found" message="Try another search or activity filter." />}</section>}

    <AlertDialog open={Boolean(userToDelete)} onOpenChange={(open) => { if (!open) onDeleteCancel(); }}><AlertDialogContent className="user-console__delete max-w-[95vw] sm:max-w-lg"><AlertDialogHeader><AlertDialogTitle>Delete {userToDelete?.name}?</AlertDialogTitle><AlertDialogDescription asChild><div><p>This permanently removes the account and its associated relationship data.</p><ul><li>Journal entries and prayer requests</li><li>Milestones, responses, and devotional progress</li><li>Scripture memory and notification history</li>{userToDelete?.partnerId && <li><strong>Their partner, {userToDelete.partnerName}, will be disconnected.</strong></li>}</ul><p className="user-console__warning">This action cannot be undone.</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={isDeleting}>Keep account</AlertDialogCancel><AlertDialogAction disabled={isDeleting} onClick={() => userToDelete && onDeleteConfirm(userToDelete.id)} className="user-console__delete-action">{isDeleting ? 'Deleting…' : 'Delete permanently'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}

function UserPreview({ user, onDelete }: { user: User | null; onDelete: (user: User) => void }) {
  if (!user) return <aside className="user-console__preview"><Empty title="Select an account" message="Profile and engagement details will appear here." /></aside>;
  const engagement = Math.min(100, (user.journalEntries * 4) + (user.prayerRequests * 5) + Math.min(user.completedDays, 30));
  return <aside className="user-console__preview" aria-label="Selected user account"><div className="user-console__profile"><span>{initials(user.name)}</span><div><span className={`user-console__status user-console__status--${user.status}`}>{user.status}</span><h2>{user.name}</h2><a href={`mailto:${user.email}`} aria-label={`Email ${user.name}`}><Mail /> {user.email}</a></div></div><div className="user-console__engagement"><div><span>Engagement signal</span><b>{engagement >= 65 ? 'Strong' : engagement >= 30 ? 'Growing' : 'Getting started'}</b></div><i><span style={{ width: `${Math.max(8, engagement)}%` }} /></i><small>Based on journey, journal, and prayer activity</small></div><dl><div><dt><CalendarDays /> Joined</dt><dd>{formatDate(user.joinedDate)}</dd></div><div><dt><Clock3 /> Last active</dt><dd>{relativeActivity(user.lastActive)}</dd></div><div><dt><FileHeart /> Journey days</dt><dd>{user.completedDays}</dd></div><div><dt><MessageSquareText /> Journal entries</dt><dd>{user.journalEntries}</dd></div><div><dt><Heart /> Prayer requests</dt><dd>{user.prayerRequests}</dd></div><div><dt><HeartHandshake /> Relationship</dt><dd>{user.partnerId ? user.partnerName || 'Connected' : 'Solo'}</dd></div></dl><div className="user-console__admin-note"><ShieldCheck /><div><strong>Account oversight</strong><span>Activity values come from the live user profile and content records.</span></div></div><button type="button" className="user-console__delete-button" onClick={() => onDelete(user)} aria-label={`Delete account for ${user.name}`}><Trash2 /> Delete account</button></aside>;
}

function CoupleCard({ couple, onSelect }: { couple: Couple; onSelect: (id: string) => void }) {
  const totalJournal = couple.user1.journalEntries + couple.user2.journalEntries;
  const totalPrayers = couple.user1.prayerRequests + couple.user2.prayerRequests;
  const active = couple.user1.status === 'active' || couple.user2.status === 'active';
  return <article className="user-console__couple-card"><header><div className="user-console__couple-mark"><span>{initials(couple.user1.name)}</span><span>{initials(couple.user2.name)}</span><Heart /></div><div><span className={`user-console__status user-console__status--${active ? 'active' : 'inactive'}`}>{active ? 'active' : 'inactive'}</span><h2>{couple.user1.name} <small>&</small> {couple.user2.name}</h2><p>Connected couple</p></div></header><div className="user-console__partners"><button type="button" onClick={() => onSelect(couple.user1.id)} aria-label={`View account for ${couple.user1.name}`}><span>{initials(couple.user1.name)}</span><div><strong>{couple.user1.name}</strong><small>{couple.user1.email}</small></div><ChevronRight /></button><button type="button" onClick={() => onSelect(couple.user2.id)} aria-label={`View account for ${couple.user2.name}`}><span>{initials(couple.user2.name)}</span><div><strong>{couple.user2.name}</strong><small>{couple.user2.email}</small></div><ChevronRight /></button></div><footer><span><FileHeart /><b>{couple.user1.completedDays + couple.user2.completedDays}</b> journey days</span><span><MessageSquareText /><b>{totalJournal}</b> journals</span><span><Heart /><b>{totalPrayers}</b> prayers</span></footer></article>;
}

function Empty({ title, message }: { title: string; message: string }) { return <div className="user-console__empty"><Eye /><h2>{title}</h2><p>{message}</p></div>; }
