import { formatUiDate } from '../../../utils/uiDateTime';
import { BrandLoader, LoadingMark } from "../../BrandLoader";
import { useCurrentLanguage } from '../../../utils/languageStore';
import { useUiCopy, UI_LOCALES } from "../../../utils/uiTranslation";
import { adminUsersMessages } from "../../../locales/adminUsers";
import { Activity, ArrowUpDown, CalendarDays, ChevronRight, Clock3, Eye, FileHeart, Heart, HeartHandshake, Mail, MessageSquareText, RefreshCw, Search, ShieldCheck, Sparkles, Trash2, UserRound, Users, X } from 'lucide-react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../ui/alert-dialog';
import type { Couple, User } from '../UsersManager';

interface Props {
  users: User[]; filteredUsers: User[]; couples: Couple[]; filteredCouples: Couple[]; selectedUser: User | null;
  selectedId: string | null; isLoading: boolean; searchQuery: string; view: 'people' | 'couples';
  statusFilter: 'all' | User['status']; connectionFilter: 'all' | 'connected' | 'solo'; sortOrder: 'activity' | 'joined' | 'name';
  userToDelete: User | null; isDeleting: boolean; onSearchChange: (value: string) => void;
  onViewChange: (view: Props['view']) => void; onStatusFilterChange: (status: Props['statusFilter']) => void;
  onConnectionFilterChange: (status: Props['connectionFilter']) => void; onSortOrderChange: (sort: Props['sortOrder']) => void;
  onSelect: (id: string) => void; onRefresh: () => void; onDeleteRequest: (user: User) => void;
  onDeleteCancel: () => void; onDeleteConfirm: (id: string) => void;
}

const formatDate = (value: string, locale: string) => formatUiDate(new Date(value), locale, { month: 'short', day: 'numeric', year: 'numeric' });
const relativeActivity = (value: string, tr: ReturnType<typeof useUiCopy>) => { const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86_400_000)); return days === 0 ? tr('Today') : days === 1 ? tr('Yesterday') : tr('{count} days ago', { count: days }); };
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export function UsersWorkspace(props: Props) {
  const tr = useUiCopy(adminUsersMessages);
  const { users, filteredUsers, couples, filteredCouples, selectedUser, selectedId, isLoading, searchQuery, view,
    statusFilter, connectionFilter, sortOrder, userToDelete, isDeleting, onSearchChange, onViewChange,
    onStatusFilterChange, onConnectionFilterChange, onSortOrderChange, onSelect, onRefresh,
    onDeleteRequest, onDeleteCancel, onDeleteConfirm } = props;
  const active = users.filter((user) => user.status === 'active').length;
  const journals = users.reduce((total, user) => total + user.journalEntries, 0);

  return <main className="user-console">
    <header className="user-console__hero"><div><span className="user-console__eyebrow"><Sparkles /> {tr("Account operations")}</span><h1>{tr("User Management")}</h1><p>{tr("Understand engagement, support connected couples, and manage member accounts with clarity and care.")}</p></div><div className="user-console__sync"><span><i className={isLoading ? 'user-console__pulse' : ''} /> {isLoading ? tr("Syncing accounts") : tr("Database connected")}</span><Button variant="outline" onClick={onRefresh} disabled={isLoading} aria-label={tr("Refresh user accounts")}>{isLoading ? <LoadingMark /> : <RefreshCw  />} {tr("Refresh")}</Button></div></header>

    <section className="user-console__metrics" aria-label={tr("User account summary")}><article><span><Users /></span><div><strong>{users.length}</strong><small>{tr("Total users")}</small></div></article><article><span><HeartHandshake /></span><div><strong>{couples.length}</strong><small>{tr("Connected couples")}</small></div></article><article><span><Activity /></span><div><strong>{active}</strong><small>{tr("Recently active")}</small></div></article><article><span><FileHeart /></span><div><strong>{journals}</strong><small>{tr("Journal entries")}</small></div></article></section>

    <section className="user-console__toolbar" aria-label={tr("User directory controls")}><div className="user-console__search"><Search /><Input value={searchQuery} onChange={(event) => onSearchChange(event.target.value)} placeholder={tr("Search name, email, or partner…")} aria-label={tr("Search users")} />{searchQuery && <button type="button" onClick={() => onSearchChange('')} aria-label={tr("Clear user search")}><X /></button>}</div><div className="user-console__views" aria-label={tr("Choose directory view")}><button type="button" data-active={view === 'people' || undefined} aria-pressed={view === 'people'} onClick={() => onViewChange('people')}><UserRound /> {tr("People")}</button><button type="button" data-active={view === 'couples' || undefined} aria-pressed={view === 'couples'} onClick={() => onViewChange('couples')}><Heart /> {tr("Couples")}</button></div><label className="user-console__select"><Activity /><span className="sr-only">{tr("Activity")}</span><select value={statusFilter} onChange={(event) => onStatusFilterChange(event.target.value as Props['statusFilter'])} aria-label={tr("Filter users by activity")}><option value="all">{tr("All activity")}</option><option value="active">{tr("Active")}</option><option value="inactive">{tr("Inactive")}</option></select></label>{view === 'people' && <label className="user-console__select"><Heart /><span className="sr-only">{tr("Connection")}</span><select value={connectionFilter} onChange={(event) => onConnectionFilterChange(event.target.value as Props['connectionFilter'])} aria-label={tr("Filter users by connection")}><option value="all">{tr("All connections")}</option><option value="connected">{tr("Connected")}</option><option value="solo">{tr("Solo")}</option></select></label>}<label className="user-console__select"><ArrowUpDown /><span className="sr-only">{tr("Sort")}</span><select value={sortOrder} onChange={(event) => onSortOrderChange(event.target.value as Props['sortOrder'])} aria-label={tr("Sort users")}><option value="activity">{tr("Recent activity")}</option><option value="joined">{tr("Recently joined")}</option><option value="name">{tr("Name A–Z")}</option></select></label></section>

    <div className="user-console__result-line" role="status"><span>{view === 'people' ? tr('{count} people', { count: filteredUsers.length }) : tr('{count} couples', { count: filteredCouples.length })}</span>{(searchQuery || statusFilter !== 'all' || connectionFilter !== 'all') && <button type="button" onClick={() => { onSearchChange(''); onStatusFilterChange('all'); onConnectionFilterChange('all'); }}>{tr("Clear filters")}</button>}</div>

    {view === 'people' ? <section className="user-console__workspace"><div className="user-console__directory" aria-label={tr("User directory")} aria-busy={isLoading}>{isLoading && <BrandLoader className="py-8" />}{!isLoading && filteredUsers.map((user, index) => { const selected = selectedId ? user.id === selectedId : selectedUser?.id === user.id; return <article className="user-console__row" data-active={selected || undefined} key={user.id}><button className="user-console__row-main" type="button" onClick={() => onSelect(user.id)} aria-label={tr('View account for {name}', { name: user.name })}><span className={`user-console__avatar user-console__avatar--${index % 4}`}>{initials(user.name)}</span><div><div className="user-console__row-title"><h2>{user.name}</h2><span className={`user-console__status user-console__status--${user.status}`}>{tr(user.status)}</span></div><p><Mail /> {user.email}</p><small>{user.partnerId ? <span><Heart /> {tr('Connected to {name}', { name: user.partnerName || tr('partner') })}</span> : <span><UserRound /> {tr("Solo account")}</span>}<span><Clock3 /> {relativeActivity(user.lastActive, tr)}</span></small></div><ChevronRight /></button></article>; })}{!isLoading && !filteredUsers.length && <Empty title={tr("No users found")} message={tr("Adjust the filters to find another account.")} />}</div><UserPreview user={selectedUser} onDelete={onDeleteRequest} /></section> : <section className="user-console__couples" aria-label={tr("Connected couples")} aria-busy={isLoading}>{isLoading && <BrandLoader className="py-8" />}{!isLoading && filteredCouples.map((couple) => <CoupleCard key={couple.id} couple={couple} onSelect={(id) => { onSelect(id); onViewChange('people'); }} />)}{!isLoading && !filteredCouples.length && <Empty title={tr("No couples found")} message={tr("Try another search or activity filter.")} />}</section>}

    <AlertDialog open={Boolean(userToDelete)} onOpenChange={(open) => { if (!open) onDeleteCancel(); }}><AlertDialogContent className="user-console__delete max-w-[95vw] sm:max-w-lg"><AlertDialogHeader><AlertDialogTitle>{tr("Delete {name}?", { name: userToDelete?.name || "" })}</AlertDialogTitle><AlertDialogDescription asChild><div><p>{tr("This permanently removes the account and its associated relationship data.")}</p><ul><li>{tr("Journal entries and prayer requests")}</li><li>{tr("Milestones, responses, and devotional progress")}</li><li>{tr("Scripture memory and notification history")}</li>{userToDelete?.partnerId && <li><strong>{tr("Their partner, {name}, will be disconnected.", { name: userToDelete.partnerName || "" })}</strong></li>}</ul><p className="user-console__warning">{tr("This action cannot be undone.")}</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={isDeleting}>{tr("Keep account")}</AlertDialogCancel><AlertDialogAction disabled={isDeleting} onClick={() => userToDelete && onDeleteConfirm(userToDelete.id)} className="user-console__delete-action">{isDeleting ? tr("Deleting…") : tr("Delete permanently")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}

function UserPreview({ user, onDelete }: { user: User | null; onDelete: (user: User) => void }) {
  const language = useCurrentLanguage();
  const tr = useUiCopy(adminUsersMessages);
  if (!user) return <aside className="user-console__preview"><Empty title={tr("Select an account")} message={tr("Profile and engagement details will appear here.")} /></aside>;
  const engagement = Math.min(100, (user.journalEntries * 4) + (user.prayerRequests * 5) + Math.min(user.completedDays, 30));
  return <aside className="user-console__preview" aria-label={tr("Selected user account")}><div className="user-console__profile"><span>{initials(user.name)}</span><div><span className={`user-console__status user-console__status--${user.status}`}>{tr(user.status)}</span><h2>{user.name}</h2><a href={`mailto:${user.email}`} aria-label={tr('Email {name}', { name: user.name })}><Mail /> {user.email}</a></div></div><div className="user-console__engagement"><div><span>{tr("Engagement signal")}</span><b>{engagement >= 65 ? tr("Strong") : engagement >= 30 ? tr("Growing") : tr("Getting started")}</b></div><i><span style={{ width: `${Math.max(8, engagement)}%` }} /></i><small>{tr("Based on journey, journal, and prayer activity")}</small></div><dl><div><dt><CalendarDays /> {tr("Joined")}</dt><dd>{formatDate(user.joinedDate, UI_LOCALES[language])}</dd></div><div><dt><Clock3 /> {tr("Last active")}</dt><dd>{relativeActivity(user.lastActive, tr)}</dd></div><div><dt><FileHeart /> {tr("Journey days")}</dt><dd>{user.completedDays}</dd></div><div><dt><MessageSquareText /> {tr("Journal entries")}</dt><dd>{user.journalEntries}</dd></div><div><dt><Heart /> {tr("Prayer requests")}</dt><dd>{user.prayerRequests}</dd></div><div><dt><HeartHandshake /> {tr("Relationship")}</dt><dd>{user.partnerId ? user.partnerName || tr("Connected") : tr("Solo")}</dd></div></dl><div className="user-console__admin-note"><ShieldCheck /><div><strong>{tr("Account oversight")}</strong><span>{tr("Activity values come from the live user profile and content records.")}</span></div></div><button type="button" className="user-console__delete-button" onClick={() => onDelete(user)} aria-label={tr('Delete account for {name}', { name: user.name })}><Trash2 /> {tr("Delete account")}</button></aside>;
}

function CoupleCard({ couple, onSelect }: { couple: Couple; onSelect: (id: string) => void }) {
  const tr = useUiCopy(adminUsersMessages);
  const totalJournal = couple.user1.journalEntries + couple.user2.journalEntries;
  const totalPrayers = couple.user1.prayerRequests + couple.user2.prayerRequests;
  const active = couple.user1.status === 'active' || couple.user2.status === 'active';
  return <article className="user-console__couple-card"><header><div className="user-console__couple-mark"><span>{initials(couple.user1.name)}</span><span>{initials(couple.user2.name)}</span><Heart /></div><div><span className={`user-console__status user-console__status--${active ? 'active' : 'inactive'}`}>{active ? tr("active") : tr("inactive")}</span><h2>{couple.user1.name} <small>&</small> {couple.user2.name}</h2><p>{tr("Connected couple")}</p></div></header><div className="user-console__partners"><button type="button" onClick={() => onSelect(couple.user1.id)} aria-label={tr('View account for {name}', { name: couple.user1.name })}><span>{initials(couple.user1.name)}</span><div><strong>{couple.user1.name}</strong><small>{couple.user1.email}</small></div><ChevronRight /></button><button type="button" onClick={() => onSelect(couple.user2.id)} aria-label={tr('View account for {name}', { name: couple.user2.name })}><span>{initials(couple.user2.name)}</span><div><strong>{couple.user2.name}</strong><small>{couple.user2.email}</small></div><ChevronRight /></button></div><footer><span><FileHeart /><b>{couple.user1.completedDays + couple.user2.completedDays}</b> {tr("journey days")}</span><span><MessageSquareText /><b>{totalJournal}</b> {tr("journals")}</span><span><Heart /><b>{totalPrayers}</b> {tr("prayers")}</span></footer></article>;
}

function Empty({ title, message }: { title: string; message: string }) { return <div className="user-console__empty"><Eye /><h2>{title}</h2><p>{message}</p></div>; }
