import { Activity, AlertTriangle, CheckCircle2, ChevronRight, Clock3, Eye, HeartHandshake, KeyRound, LockKeyhole, RefreshCw, Search, Shield, ShieldCheck, ShieldOff, Sparkles, UserRound, Users, X, XCircle } from 'lucide-react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../ui/alert-dialog';
import type { AdminUser, PrivilegeActivity, PrivilegeUser } from '../PrivilegeManager';

interface Props {
  users: PrivilegeUser[]; filteredUsers: PrivilegeUser[]; admins: AdminUser[]; activity: PrivilegeActivity[]; isLoading: boolean;
  searchTerm: string; view: 'directory' | 'admins' | 'activity'; roleFilter: 'all' | 'admin' | 'member';
  selectedUser: PrivilegeUser | null; selectedId: string | null; processingUserId: string | null;
  pendingChange: { action: 'grant' | 'revoke'; user: PrivilegeUser } | null;
  onSearchChange: (value: string) => void; onViewChange: (view: Props['view']) => void;
  onRoleFilterChange: (role: Props['roleFilter']) => void; onSelect: (id: string) => void; onRefresh: () => void;
  onChangeRequest: (action: 'grant' | 'revoke', user: PrivilegeUser) => void; onChangeCancel: () => void; onChangeConfirm: () => void;
}
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const formatTime = (value: string) => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });

export function PrivilegeWorkspace(props: Props) {
  const { users, filteredUsers, admins, activity, isLoading, searchTerm, view, roleFilter, selectedUser, selectedId,
    processingUserId, pendingChange, onSearchChange, onViewChange, onRoleFilterChange, onSelect, onRefresh,
    onChangeRequest, onChangeCancel, onChangeConfirm } = props;
  const adminRate = users.length ? Math.round((admins.length / users.length) * 100) : 0;
  const recentChanges = activity.filter((item) => Date.now() - new Date(item.timestamp).getTime() <= 30 * 86_400_000).length;
  return <main className="privilege-console">
    <header className="privilege-console__hero"><div><span className="privilege-console__eyebrow"><Sparkles /> Identity & access</span><h1>User Privileges</h1><p>Grant administrator access deliberately, review every change, and keep powerful permissions accountable.</p></div><div className="privilege-console__hero-status"><span><LockKeyhole /> Protected admin area</span><Button variant="outline" onClick={onRefresh} disabled={isLoading} aria-label="Refresh privilege data"><RefreshCw className={isLoading ? 'privilege-console__spin' : ''} /> Refresh</Button></div></header>
    <section className="privilege-console__metrics" aria-label="Access-control summary"><article><span><Users /></span><div><strong>{users.length}</strong><small>Registered users</small></div></article><article><span><ShieldCheck /></span><div><strong>{admins.length}</strong><small>Administrators</small></div></article><article><span><KeyRound /></span><div><strong>{adminRate}%</strong><small>Privileged accounts</small></div></article><article><span><Activity /></span><div><strong>{recentChanges}</strong><small>Changes in 30 days</small></div></article></section>
    <section className="privilege-console__toolbar" aria-label="Privilege directory controls"><div className="privilege-console__search"><Search /><Input value={searchTerm} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search name or email…" aria-label="Search privilege users" />{searchTerm && <button type="button" onClick={() => onSearchChange('')} aria-label="Clear privilege search"><X /></button>}</div><nav aria-label="Privilege views"><button type="button" data-active={view === 'directory' || undefined} aria-pressed={view === 'directory'} onClick={() => onViewChange('directory')}><Users /> Directory</button><button type="button" data-active={view === 'admins' || undefined} aria-pressed={view === 'admins'} onClick={() => onViewChange('admins')}><ShieldCheck /> Admins <span>{admins.length}</span></button><button type="button" data-active={view === 'activity' || undefined} aria-pressed={view === 'activity'} onClick={() => onViewChange('activity')}><Clock3 /> Audit log</button></nav>{view === 'directory' && <label className="privilege-console__select"><Shield /><span className="sr-only">Role</span><select aria-label="Filter users by role" value={roleFilter} onChange={(event) => onRoleFilterChange(event.target.value as Props['roleFilter'])}><option value="all">All roles</option><option value="admin">Administrators</option><option value="member">Members</option></select></label>}</section>

    {view === 'directory' && <><div className="privilege-console__result-line" role="status"><span>{filteredUsers.length} accounts</span>{(searchTerm || roleFilter !== 'all') && <button type="button" onClick={() => { onSearchChange(''); onRoleFilterChange('all'); }}>Clear filters</button>}</div><section className="privilege-console__workspace"><div className="privilege-console__directory" aria-label="Privilege user directory" aria-busy={isLoading}>{isLoading && [...Array(5)].map((_, index) => <div className="privilege-console__skeleton" key={index} />)}{!isLoading && filteredUsers.map((user, index) => { const active = selectedId ? user.id === selectedId : selectedUser?.id === user.id; return <article key={user.id} className="privilege-console__row" data-active={active || undefined}><button type="button" onClick={() => onSelect(user.id)} aria-label={`Review privileges for ${user.name}`}><span className={`privilege-console__avatar privilege-console__avatar--${index % 4}`}>{initials(user.name)}</span><div><div><h2>{user.name}</h2><RoleBadge admin={user.isAdmin} /></div><p>{user.email}</p><small>{user.hasPartner ? <><HeartHandshake /> Connected account</> : <><UserRound /> Individual account</>}</small></div><ChevronRight /></button></article>; })}{!isLoading && !filteredUsers.length && <Empty icon={Users} title="No accounts found" message="Try another name, email, or role filter." />}</div><AccessPreview user={selectedUser} processing={processingUserId} onChange={onChangeRequest} /></section></>}
    {view === 'admins' && <section className="privilege-console__admins" aria-label="Administrator accounts" aria-busy={isLoading}>{isLoading && [...Array(3)].map((_, index) => <div className="privilege-console__skeleton" key={index} />)}{!isLoading && admins.map((admin, index) => <article key={admin.id}><div className="privilege-console__admin-mark"><ShieldCheck /></div><div><span>Administrator</span><h2>{admin.name}</h2><p>{admin.email}</p><small>Access granted {formatDate(admin.addedAt)}</small></div><button type="button" onClick={() => { const user = users.find((item) => item.id === admin.id); if (user) onChangeRequest('revoke', user); }} disabled={processingUserId === admin.id} aria-label={`Revoke administrator access from ${admin.name}`}><ShieldOff /> Revoke</button></article>)}{!isLoading && !admins.length && <Empty icon={ShieldOff} title="No administrators found" message="Grant access from the user directory." />}</section>}
    {view === 'activity' && <section className="privilege-console__audit" aria-label="Privilege audit log" aria-busy={isLoading}>{isLoading && [...Array(4)].map((_, index) => <div className="privilege-console__skeleton" key={index} />)}{!isLoading && activity.map((item, index) => <article key={item.id || `${item.timestamp}-${index}`}><span className={`privilege-console__audit-icon privilege-console__audit-icon--${item.action}`}>{item.action === 'granted' ? <CheckCircle2 /> : <XCircle />}</span><div><span>{item.action === 'granted' ? 'Administrator access granted' : 'Administrator access revoked'}</span><h2>{item.targetUser.name || item.targetUser.email}</h2><p><strong>{item.performedBy.name || item.performedBy.email}</strong> {item.action === 'granted' ? 'granted access to' : 'revoked access from'} {item.targetUser.email}</p><time dateTime={item.timestamp}>{formatTime(item.timestamp)}</time></div></article>)}{!isLoading && !activity.length && <Empty icon={Clock3} title="No privilege changes" message="Grant and revoke events will appear here." />}</section>}
    <section className="privilege-console__notice"><AlertTriangle /><div><strong>Full-access permission</strong><p>Administrators can manage content, users, privileges, and system configuration. Every change is recorded in the audit log.</p></div></section>
    <AlertDialog open={Boolean(pendingChange)} onOpenChange={(open) => { if (!open) onChangeCancel(); }}><AlertDialogContent className="privilege-console__dialog max-w-[95vw] sm:max-w-lg"><AlertDialogHeader><div className={`privilege-console__dialog-icon privilege-console__dialog-icon--${pendingChange?.action}`}>{pendingChange?.action === 'grant' ? <ShieldCheck /> : <ShieldOff />}</div><AlertDialogTitle>{pendingChange?.action === 'grant' ? 'Grant administrator access?' : 'Revoke administrator access?'}</AlertDialogTitle><AlertDialogDescription asChild><div><p>{pendingChange?.action === 'grant' ? `${pendingChange.user.name} will receive full access to the admin console.` : `${pendingChange?.user.name} will immediately lose access to all administrator tools.`}</p>{pendingChange?.action === 'grant' && <ul><li>Content and publishing management</li><li>User and community data</li><li>Privilege and system configuration</li></ul>}<p className="privilege-console__dialog-user">{pendingChange?.user.email}</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={Boolean(processingUserId)}>Cancel</AlertDialogCancel><AlertDialogAction onClick={onChangeConfirm} disabled={Boolean(processingUserId)} className={pendingChange?.action === 'revoke' ? 'privilege-console__revoke-action' : 'privilege-console__grant-action'}>{processingUserId ? 'Applying change…' : pendingChange?.action === 'grant' ? 'Grant full access' : 'Revoke access'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
function RoleBadge({ admin }: { admin: boolean }) { return <span className={`privilege-console__role privilege-console__role--${admin ? 'admin' : 'member'}`}>{admin ? <ShieldCheck /> : <UserRound />}{admin ? 'Administrator' : 'Member'}</span>; }
function AccessPreview({ user, processing, onChange }: { user: PrivilegeUser | null; processing: string | null; onChange: (action: 'grant' | 'revoke', user: PrivilegeUser) => void }) { if (!user) return <aside className="privilege-console__preview"><Empty icon={Eye} title="Select an account" message="Its role and access scope will appear here." /></aside>; return <aside className="privilege-console__preview" aria-label="Selected account privileges"><header><span>{initials(user.name)}</span><div><RoleBadge admin={user.isAdmin} /><h2>{user.name}</h2><p>{user.email}</p></div></header><section className={`privilege-console__access privilege-console__access--${user.isAdmin ? 'admin' : 'member'}`}><div>{user.isAdmin ? <ShieldCheck /> : <UserRound />}<span><strong>{user.isAdmin ? 'Full administrator access' : 'Standard member access'}</strong><small>{user.isAdmin ? 'Can access every admin console feature' : 'Cannot access administrator tools'}</small></span></div></section><dl><div><dt>Account created</dt><dd>{formatDate(user.createdAt)}</dd></div><div><dt>Relationship</dt><dd>{user.hasPartner ? 'Connected' : 'Individual'}</dd></div><div><dt>Authentication role</dt><dd>{user.isAdmin ? 'Administrator' : 'Member'}</dd></div><div><dt>Admin scope</dt><dd>{user.isAdmin ? 'Full access' : 'No access'}</dd></div></dl><div className="privilege-console__scope"><strong>{user.isAdmin ? 'Access includes' : 'Protected capabilities'}</strong>{['Dashboard & analytics', 'Content publishing', 'Character House game studio', 'User management', 'Privilege controls'].map((item) => <span key={item}>{user.isAdmin ? <CheckCircle2 /> : <LockKeyhole />}{item}</span>)}</div><Button onClick={() => onChange(user.isAdmin ? 'revoke' : 'grant', user)} disabled={processing === user.id} className={user.isAdmin ? 'privilege-console__revoke-button' : 'privilege-console__grant-button'} aria-label={`${user.isAdmin ? 'Revoke administrator access from' : 'Grant administrator access to'} ${user.name}`}>{user.isAdmin ? <ShieldOff /> : <ShieldCheck />}{processing === user.id ? 'Applying change…' : user.isAdmin ? 'Revoke administrator access' : 'Grant administrator access'}</Button></aside>; }
function Empty({ icon: Icon, title, message }: { icon: typeof Eye; title: string; message: string }) { return <div className="privilege-console__empty"><Icon /><h2>{title}</h2><p>{message}</p></div>; }
