/*\n  # Initialize HabeshaConnect Database Schema\n\n  1. Core Tables\n    - user_profiles: User information and preferences\n    - admin_users: Admin access control\n    - exchange_rates: Currency exchange rates\n    - room_listings: Room/apartment listings\n    - worship_places: Ethiopian churches and community centers\n    - visa_info: Visa types and requirements\n    - community_announcements: Events and announcements\n    - lists: FAQs, resources, guides\n    - uploaded_files: File management system\n    \n  2. Security\n    - Enable RLS on all tables\n    - Public read access for most content\n    - Admin full access for management\n    - User-specific write permissions\n*/\n\n-- User Profiles Table\nCREATE TABLE IF NOT EXISTS user_profiles (\n  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,\n  full_name text NOT NULL,\n  phone_number text,\n  preferred_language text DEFAULT 'en',\n  location_uae text,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own profile"\n  ON user_profiles FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can update own profile"\n  ON user_profiles FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can insert own profile"\n  ON user_profiles FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\n-- Admin Users Table\nCREATE TABLE IF NOT EXISTS admin_users (\n  id uuid PRIMARY KEY REFERENCES user_profiles(id) ON DELETE CASCADE,\n  email text UNIQUE NOT NULL,\n  role text NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin', 'moderator')),\n  permissions jsonb DEFAULT '[]'::jsonb,\n  created_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "View own admin status"\n  ON admin_users FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\n-- Helper function to check admin status\nCREATE OR REPLACE FUNCTION is_admin(user_id uuid)\nRETURNS boolean AS $$\nBEGIN\n  RETURN EXISTS (SELECT 1 FROM admin_users WHERE id = user_id);
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\nCREATE POLICY "Admins can view all admin users"\n  ON admin_users FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Super admins can add new admins"\n  ON admin_users FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM admin_users \n      WHERE id = auth.uid() AND role = 'super_admin'\n    )\n  );
\n\nCREATE POLICY "Super admins can update admins"\n  ON admin_users FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM admin_users \n      WHERE id = auth.uid() AND role = 'super_admin'\n    )\n  );
\n\n-- Exchange Rates Table\nCREATE TABLE IF NOT EXISTS exchange_rates (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,\n  currency_from text NOT NULL,\n  currency_to text NOT NULL,\n  rate numeric(10, 4) NOT NULL,\n  source text NOT NULL DEFAULT 'user_submission',\n  location text,\n  is_verified boolean DEFAULT false,\n  verification_score integer DEFAULT 0,\n  created_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE exchange_rates ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view exchange rates"\n  ON exchange_rates FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Authenticated users can submit rates"\n  ON exchange_rates FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Admins can update rates"\n  ON exchange_rates FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can delete rates"\n  ON exchange_rates FOR DELETE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\n-- Room Listings Table\nCREATE TABLE IF NOT EXISTS room_listings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,\n  title text NOT NULL,\n  description text NOT NULL,\n  location text NOT NULL,\n  city text NOT NULL,\n  latitude numeric(10, 7),\n  longitude numeric(10, 7),\n  monthly_rent_aed numeric(10, 2) NOT NULL,\n  room_type text NOT NULL CHECK (room_type IN ('private', 'shared', 'studio')),\n  gender_preference text DEFAULT 'any' CHECK (gender_preference IN ('male', 'female', 'any')),\n  available_from date DEFAULT CURRENT_DATE,\n  amenities jsonb DEFAULT '[]'::jsonb,\n  contact_phone text NOT NULL,\n  images jsonb DEFAULT '[]'::jsonb,\n  is_available boolean DEFAULT true,\n  view_count integer DEFAULT 0,\n  created_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE room_listings ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view available rooms"\n  ON room_listings FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Authenticated users can post rooms"\n  ON room_listings FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own listings"\n  ON room_listings FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id OR is_admin(auth.uid()));
\n\nCREATE POLICY "Users can delete own listings"\n  ON room_listings FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id OR is_admin(auth.uid()));
\n\n-- Function to increment room view count\nCREATE OR REPLACE FUNCTION increment_room_view_count(listing_id uuid)\nRETURNS void AS $$\nBEGIN\n  UPDATE room_listings \n  SET view_count = view_count + 1 \n  WHERE id = listing_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Worship Places Table\nCREATE TABLE IF NOT EXISTS worship_places (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  name text NOT NULL,\n  denomination text,\n  address text NOT NULL,\n  city text NOT NULL,\n  latitude numeric(10, 7),\n  longitude numeric(10, 7),\n  contact_phone text,\n  contact_email text,\n  website text,\n  service_times jsonb DEFAULT '[]'::jsonb,\n  languages jsonb DEFAULT '["Amharic", "English"]'::jsonb,\n  amenities jsonb DEFAULT '[]'::jsonb,\n  is_verified boolean DEFAULT false,\n  created_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE worship_places ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view worship places"\n  ON worship_places FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Admins can manage worship places"\n  ON worship_places FOR ALL\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\n-- Visa Info Table\nCREATE TABLE IF NOT EXISTS visa_info (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  visa_type text NOT NULL,\n  description text NOT NULL,\n  eligibility text NOT NULL,\n  required_documents jsonb DEFAULT '[]'::jsonb,\n  processing_time text,\n  fee_amount numeric(10, 2),\n  fee_currency text DEFAULT 'AED',\n  duration text,\n  is_active boolean DEFAULT true,\n  sort_order integer DEFAULT 0,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE visa_info ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view visa info"\n  ON visa_info FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Admins can manage visa info"\n  ON visa_info FOR ALL\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\n-- Community Announcements Table\nCREATE TABLE IF NOT EXISTS community_announcements (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  title text NOT NULL,\n  description text NOT NULL,\n  event_date timestamptz,\n  location text,\n  organizer text,\n  contact_info text,\n  category text DEFAULT 'general',\n  priority text DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),\n  is_featured boolean DEFAULT false,\n  image_url text,\n  created_at timestamptz DEFAULT now(),\n  expires_at timestamptz\n);
\n\nALTER TABLE community_announcements ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view announcements"\n  ON community_announcements FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Admins can manage announcements"\n  ON community_announcements FOR ALL\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\n-- Lists Table (FAQs, Resources)\nCREATE TABLE IF NOT EXISTS lists (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  title text NOT NULL,\n  description text,\n  type text NOT NULL CHECK (type IN ('faq', 'resource', 'guide', 'link')),\n  content jsonb NOT NULL,\n  category text,\n  is_published boolean DEFAULT true,\n  sort_order integer DEFAULT 0,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE lists ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view published lists"\n  ON lists FOR SELECT\n  TO public\n  USING (is_published = true);
\n\nCREATE POLICY "Admins can view all lists"\n  ON lists FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can create lists"\n  ON lists FOR INSERT\n  TO authenticated\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can update lists"\n  ON lists FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can delete lists"\n  ON lists FOR DELETE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\n-- Uploaded Files Table\nCREATE TABLE IF NOT EXISTS uploaded_files (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,\n  file_name text NOT NULL,\n  file_path text NOT NULL,\n  file_type text NOT NULL,\n  file_size bigint NOT NULL,\n  mime_type text,\n  category text,\n  is_public boolean DEFAULT false,\n  created_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE uploaded_files ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own files"\n  ON uploaded_files FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id OR is_public = true);
\n\nCREATE POLICY "Admins can view all files"\n  ON uploaded_files FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can upload files"\n  ON uploaded_files FOR INSERT\n  TO authenticated\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can update files"\n  ON uploaded_files FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can delete files"\n  ON uploaded_files FOR DELETE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS idx_exchange_rates_created_at ON exchange_rates(created_at DESC);
\nCREATE INDEX IF NOT EXISTS idx_exchange_rates_currencies ON exchange_rates(currency_from, currency_to);
\nCREATE INDEX IF NOT EXISTS idx_room_listings_city ON room_listings(city);
\nCREATE INDEX IF NOT EXISTS idx_room_listings_available ON room_listings(is_available);
\nCREATE INDEX IF NOT EXISTS idx_worship_places_city ON worship_places(city);
\nCREATE INDEX IF NOT EXISTS idx_visa_info_active ON visa_info(is_active);
\n;
