import { formatUiDate } from '../../../utils/uiDateTime';
import { LoadingMark } from '../../BrandLoader';
import { useCurrentLanguage } from '../../../utils/languageStore';
import { UI_LOCALES, useUiCopy } from "../../../utils/uiTranslation";
import { adminLandingMessages } from "../../../locales/adminLanding";
import type { ReactNode } from 'react';
import { BookOpen, Check, ChevronRight, Eye, FileText, Heart, Image, LayoutTemplate, Mail, MessageSquare, Monitor, Plus, RefreshCw, RotateCcw, Save, Smartphone, Sparkles, Star, Trash2, TrendingUp, Users } from 'lucide-react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Label } from '../../ui/label';
import { Textarea } from '../../ui/textarea';
import type { LandingContent, NewsletterSubscriber } from '../LandingPageManager';

type Section = 'hero' | 'features' | 'why' | 'stats' | 'testimonials' | 'faqs' | 'cta';
interface Props {
  content: LandingContent; subscribers: NewsletterSubscriber[]; subscribersCount: number;
  isLoading: boolean; isSaving: boolean; isDirty: boolean; activeView: 'content' | 'media' | 'subscribers';
  activeSection: Section; media: ReactNode; onViewChange: (view: Props['activeView']) => void;
  onSectionChange: (section: Section) => void; onContentChange: (content: LandingContent) => void;
  onSave: () => void; onReload: () => void; onReset: () => void;
}

const sectionMeta: Array<{ id: Section; label: string; icon: typeof Heart }> = [
  { id: 'hero', label: 'Hero message', icon: Heart }, { id: 'features', label: 'Feature grid', icon: Sparkles },
  { id: 'why', label: 'Why TwoBeOne', icon: BookOpen }, { id: 'stats', label: 'Social proof', icon: TrendingUp },
  { id: 'testimonials', label: 'Testimonials', icon: Star }, { id: 'faqs', label: 'FAQs', icon: MessageSquare },
  { id: 'cta', label: 'Final CTA', icon: ChevronRight },
];
const icons = ['BookOpen', 'MessageSquare', 'Heart', 'Users', 'Sparkles', 'TrendingUp', 'Shield', 'Zap', 'Globe', 'Star'];
const iconLabels: Record<string,string> = { BookOpen: 'Book', MessageSquare: 'Conversation', Heart: 'Heart', Users: 'People', Sparkles: 'Sparkles', TrendingUp: 'Growth', Shield: 'Shield', Zap: 'Lightning', Globe: 'Globe', Star: 'Star' };
const colorLabels = ['Amber', 'Sky', 'Rose', 'Rose and sky', 'Green'];
const colors = ['from-warning-500 to-warning-500', 'from-sky-500 to-sky-600', 'from-primary-500 to-primary-600', 'from-primary-500 to-sky-500', 'from-success-500 to-success-700'];

export function LandingPageWorkspace(props: Props) {
  const tr = useUiCopy(adminLandingMessages);
  const language = useCurrentLanguage();
  const { content, subscribers, subscribersCount, isLoading, isSaving, isDirty, activeView, activeSection,
    media, onViewChange, onSectionChange, onContentChange, onSave, onReload, onReset } = props;
  const totalBlocks = content.features.length + content.stats.length + content.testimonials.length + content.faqs.length;
  return <main className="landing-console">
    <header className="landing-console__hero"><div><span className="landing-console__eyebrow"><Sparkles /> {' '}{tr("Publishing studio")}</span><h1>{tr("Landing Page")}</h1><p>{tr("Craft the first impression, preview the story, and publish updates from one focused workspace.")}</p></div><div className="landing-console__hero-actions"><span className={isDirty ? 'landing-console__state landing-console__state--dirty' : 'landing-console__state'}>{isDirty ? <><i /> {' '}{tr("Unsaved changes")}</> : <><Check /> {' '}{tr("All changes saved")}</>}</span><div><Button variant="outline" onClick={onReload} disabled={isLoading} aria-label={tr("Reload landing page content")}>{isLoading ? <LoadingMark /> : <RefreshCw />} {' '}{tr("Reload")}</Button><Button onClick={onSave} disabled={isSaving || !isDirty} className="landing-console__primary" aria-label={tr("Save landing page changes")}>{isSaving ? <LoadingMark /> : <Save />} {isSaving ? tr("Saving…") : tr("Save changes")}</Button></div></div></header>

    <section className="landing-console__metrics" aria-label={tr("Landing page summary")}><article><span><LayoutTemplate /></span><div><strong>7</strong><small>{tr("Page sections")}</small></div></article><article><span><FileText /></span><div><strong>{totalBlocks}</strong><small>{tr("Content blocks")}</small></div></article><article><span><Star /></span><div><strong>{content.testimonials.length}</strong><small>{tr("Testimonials")}</small></div></article><article><span><Mail /></span><div><strong>{subscribersCount}</strong><small>{tr("Subscribers")}</small></div></article></section>

    <nav className="landing-console__views" aria-label={tr("Landing page workspace")}><button type="button" data-active={activeView === 'content' || undefined} onClick={() => onViewChange('content')} aria-pressed={activeView === 'content'}><LayoutTemplate /> {' '}{tr("Content studio")}</button><button type="button" data-active={activeView === 'media' || undefined} onClick={() => onViewChange('media')} aria-pressed={activeView === 'media'}><Image /> {' '}{tr("Media library")}</button><button type="button" data-active={activeView === 'subscribers' || undefined} onClick={() => onViewChange('subscribers')} aria-pressed={activeView === 'subscribers'}><Mail /> {' '}{tr("Subscribers")}{' '}<span>{subscribersCount}</span></button></nav>

    {activeView === 'content' && <section className="landing-console__workspace"><aside className="landing-console__sections" aria-label={tr("Landing page sections")}><div><span>{tr("Page structure")}</span><small>{tr('{count} editable blocks', { count: totalBlocks })}</small></div>{sectionMeta.map(({ id, label, icon: Icon }, index) => <button type="button" key={id} data-active={activeSection === id || undefined} onClick={() => onSectionChange(id)} aria-current={activeSection === id ? 'step' : undefined}><span>{String(index + 1).padStart(2, '0')}</span><Icon /><div><strong>{tr(label)}</strong><small>{sectionCount(id, content, tr)}</small></div><ChevronRight /></button>)}<button className="landing-console__reset" type="button" onClick={onReset}><RotateCcw /> {' '}{tr("Reset default content")}</button></aside><div className="landing-console__editor"><Editor section={activeSection} content={content} onChange={onContentChange} /></div><LandingPreview content={content} /></section>}
    {activeView === 'media' && <section className="landing-console__panel"><div className="landing-console__panel-title"><div><Image /><span><h2>{tr("Media library")}</h2><p>{tr("Manage the screenshots used to showcase the app.")}</p></span></div></div>{media}</section>}
    {activeView === 'subscribers' && <section className="landing-console__panel"><div className="landing-console__panel-title"><div><Mail /><span><h2>{tr("Newsletter audience")}</h2><p>{tr("People who asked to hear about product updates and relationship resources.")}</p></span></div><b>{tr('{count} total', { count: subscribersCount })}</b></div><div className="landing-console__subscribers">{subscribers.map((subscriber, index) => <article key={`${subscriber.email}-${index}`}><span>{subscriber.email.slice(0, 1).toUpperCase()}</span><div><strong>{subscriber.email}</strong><small>{tr('Subscribed {date}', { date: formatUiDate(new Date(subscriber.subscribedAt), UI_LOCALES[language]) })}</small></div><i>{subscriber.status || tr("active")}</i></article>)}{!subscribers.length && <div className="landing-console__empty"><Mail /><h2>{tr("No subscribers yet")}</h2><p>{tr("New newsletter signups will appear here automatically.")}</p></div>}</div></section>}
  </main>;
}

function sectionCount(section: Section, content: LandingContent, tr: ReturnType<typeof useUiCopy>) { if (section === 'features') return tr('{count} feature cards', { count: content.features.length }); if (section === 'stats') return tr('{count} statistics', { count: content.stats.length }); if (section === 'testimonials') return tr('{count} stories', { count: content.testimonials.length }); if (section === 'faqs') return tr('{count} questions', { count: content.faqs.length }); if (section === 'why') return tr('{count} reasons', { count: content.whySection.reasons.length }); return tr(section === 'hero' ? 'Headline & Scripture' : 'Conversion message'); }
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="landing-editor__field"><Label>{label}</Label>{children}{hint && <small>{hint}</small>}</label>; }
function SectionHeading({ number, title, description }: { number: string; title: string; description: string }) { return <div className="landing-editor__heading"><span>{number}</span><div><h2>{title}</h2><p>{description}</p></div></div>; }

function Editor({ section, content, onChange }: { section: Section; content: LandingContent; onChange: (content: LandingContent) => void }) {
  const tr = useUiCopy(adminLandingMessages);
  const update = <K extends keyof LandingContent>(key: K, value: LandingContent[K]) => onChange({ ...content, [key]: value });
  if (section === 'hero') return <div className="landing-editor"><SectionHeading number="01" title={tr("Hero message")} description={tr("Make the value clear within the first few seconds.")} /><Field label={tr("Eyebrow badge")}><Input value={content.hero.badge} onChange={(e) => update('hero', { ...content.hero, badge: e.target.value })} /></Field><Field label={tr("Main headline")} hint={tr('{count} characters', { count: content.hero.title.length })}><Input value={content.hero.title} onChange={(e) => update('hero', { ...content.hero, title: e.target.value })} /></Field><Field label={tr("Highlighted headline")}><Input value={content.hero.subtitle} onChange={(e) => update('hero', { ...content.hero, subtitle: e.target.value })} /></Field><Field label={tr("Supporting description")} hint={tr('{count} characters', { count: content.hero.description.length })}><Textarea rows={4} value={content.hero.description} onChange={(e) => update('hero', { ...content.hero, description: e.target.value })} /></Field><div className="landing-editor__grid"><Field label={tr("Scripture")}><Textarea rows={4} value={content.hero.scripture.text} onChange={(e) => update('hero', { ...content.hero, scripture: { ...content.hero.scripture, text: e.target.value } })} /></Field><div><Field label={tr("Reference")}><Input value={content.hero.scripture.reference} onChange={(e) => update('hero', { ...content.hero, scripture: { ...content.hero.scripture, reference: e.target.value } })} /></Field><div className="landing-editor__grid"><Field label={tr("Couples count")}><Input value={content.hero.socialProof.couplesCount} onChange={(e) => update('hero', { ...content.hero, socialProof: { ...content.hero.socialProof, couplesCount: e.target.value } })} /></Field><Field label={tr("Rating")}><Input type="number" min="1" max="5" value={content.hero.socialProof.rating} onChange={(e) => update('hero', { ...content.hero, socialProof: { ...content.hero.socialProof, rating: Number(e.target.value) } })} /></Field></div></div></div></div>;
  if (section === 'features') return <ArrayEditor heading={tr("Feature grid")} description={tr("Show the core experiences couples receive.")} addLabel={tr("Add feature")} onAdd={() => update('features', [...content.features, { title: 'New feature', description: 'Describe the value for couples.', icon: 'Heart', color: colors[0] }])}>{content.features.map((item, index) => <ItemCard key={index} index={index} label={item.title || tr("Untitled feature")} onDelete={() => update('features', content.features.filter((_, i) => i !== index))}><Field label={tr("Title")}><Input value={item.title} onChange={(e) => updateAt('features', content, index, { ...item, title: e.target.value }, onChange)} /></Field><Field label={tr("Description")}><Textarea rows={3} value={item.description} onChange={(e) => updateAt('features', content, index, { ...item, description: e.target.value }, onChange)} /></Field><div className="landing-editor__grid"><Field label={tr("Icon")}><select value={item.icon} onChange={(e) => updateAt('features', content, index, { ...item, icon: e.target.value }, onChange)}>{icons.map((icon) => <option key={icon} value={icon}>{tr(iconLabels[icon])}</option>)}</select></Field><Field label={tr("Theme")}><select value={item.color} onChange={(e) => updateAt('features', content, index, { ...item, color: e.target.value }, onChange)}>{colors.map((color, index) => <option key={color} value={color}>{tr(colorLabels[index])}</option>)}</select></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'why') return <div className="landing-editor"><SectionHeading number="03" title={tr("Why TwoBeOne")} description={tr("Explain the deeper purpose and trust promise.")} /><Field label={tr("Badge")}><Input value={content.whySection.badge} onChange={(e) => update('whySection', { ...content.whySection, badge: e.target.value })} /></Field><Field label={tr("Title")}><Input value={content.whySection.title} onChange={(e) => update('whySection', { ...content.whySection, title: e.target.value })} /></Field><Field label={tr("Description")}><Textarea rows={4} value={content.whySection.description} onChange={(e) => update('whySection', { ...content.whySection, description: e.target.value })} /></Field>{content.whySection.reasons.map((reason, index) => <ItemCard key={index} index={index} label={reason.title}><div className="landing-editor__grid"><Field label={tr("Icon")}><select value={reason.icon} onChange={(e) => updateReason(content, index, { ...reason, icon: e.target.value }, onChange)}>{icons.map((icon) => <option key={icon} value={icon}>{tr(iconLabels[icon])}</option>)}</select></Field><Field label={tr("Title")}><Input value={reason.title} onChange={(e) => updateReason(content, index, { ...reason, title: e.target.value }, onChange)} /></Field></div><Field label={tr("Description")}><Textarea rows={2} value={reason.description} onChange={(e) => updateReason(content, index, { ...reason, description: e.target.value }, onChange)} /></Field></ItemCard>)}</div>;
  if (section === 'stats') return <ArrayEditor heading={tr("Social proof")} description={tr("Keep proof points concise and credible.")} addLabel={tr("Add statistic")} onAdd={() => update('stats', [...content.stats, { label: 'New metric', value: '0', gradient: 'from-primary-50 to-primary-50' }])}>{content.stats.map((item, index) => <ItemCard key={index} index={index} label={item.label} onDelete={() => update('stats', content.stats.filter((_, i) => i !== index))}><div className="landing-editor__grid"><Field label={tr("Value")}><Input value={item.value} onChange={(e) => updateAt('stats', content, index, { ...item, value: e.target.value }, onChange)} /></Field><Field label={tr("Label")}><Input value={item.label} onChange={(e) => updateAt('stats', content, index, { ...item, label: e.target.value }, onChange)} /></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'testimonials') return <ArrayEditor heading={tr("Testimonials")} description={tr("Share authentic stories from couples.")} addLabel={tr("Add testimonial")} onAdd={() => update('testimonials', [...content.testimonials, { name: 'New couple', location: 'City', image: '💑', quote: 'Share their story here.', rating: 5, married: '1 year' }])}>{content.testimonials.map((item, index) => <ItemCard key={index} index={index} label={item.name} onDelete={() => update('testimonials', content.testimonials.filter((_, i) => i !== index))}><div className="landing-editor__grid"><Field label={tr("Couple")}><Input value={item.name} onChange={(e) => updateAt('testimonials', content, index, { ...item, name: e.target.value }, onChange)} /></Field><Field label={tr("Location")}><Input value={item.location} onChange={(e) => updateAt('testimonials', content, index, { ...item, location: e.target.value }, onChange)} /></Field></div><Field label={tr("Quote")}><Textarea rows={4} value={item.quote} onChange={(e) => updateAt('testimonials', content, index, { ...item, quote: e.target.value }, onChange)} /></Field><div className="landing-editor__grid landing-editor__grid--three"><Field label={tr("Avatar")}><Input value={item.image} onChange={(e) => updateAt('testimonials', content, index, { ...item, image: e.target.value }, onChange)} /></Field><Field label={tr("Rating")}><Input type="number" min="1" max="5" value={item.rating} onChange={(e) => updateAt('testimonials', content, index, { ...item, rating: Number(e.target.value) }, onChange)} /></Field><Field label={tr("Together")}><Input value={item.married} onChange={(e) => updateAt('testimonials', content, index, { ...item, married: e.target.value }, onChange)} /></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'faqs') return <ArrayEditor heading={tr("Frequently asked questions")} description={tr("Resolve hesitation before a visitor leaves.")} addLabel={tr("Add FAQ")} onAdd={() => update('faqs', [...content.faqs, { question: 'New question?', answer: 'Add a clear answer.' }])}>{content.faqs.map((item, index) => <ItemCard key={index} index={index} label={item.question} onDelete={() => update('faqs', content.faqs.filter((_, i) => i !== index))}><Field label={tr("Question")}><Input value={item.question} onChange={(e) => updateAt('faqs', content, index, { ...item, question: e.target.value }, onChange)} /></Field><Field label={tr("Answer")}><Textarea rows={3} value={item.answer} onChange={(e) => updateAt('faqs', content, index, { ...item, answer: e.target.value }, onChange)} /></Field></ItemCard>)}</ArrayEditor>;
  return <div className="landing-editor"><SectionHeading number="07" title={tr("Final call to action")} description={tr("End with one confident, low-friction next step.")} /><Field label={tr("Title")}><Input value={content.cta.title} onChange={(e) => update('cta', { ...content.cta, title: e.target.value })} /></Field><Field label={tr("Description")}><Textarea rows={3} value={content.cta.description} onChange={(e) => update('cta', { ...content.cta, description: e.target.value })} /></Field><div className="landing-editor__grid"><Field label={tr("Newsletter label")}><Input value={content.cta.newsletterLabel} onChange={(e) => update('cta', { ...content.cta, newsletterLabel: e.target.value })} /></Field><Field label={tr("Button text")}><Input value={content.cta.buttonText} onChange={(e) => update('cta', { ...content.cta, buttonText: e.target.value })} /></Field></div><Field label={tr("Reassurance text")}><Input value={content.cta.footer} onChange={(e) => update('cta', { ...content.cta, footer: e.target.value })} /></Field></div>;
}

function updateAt<K extends 'features' | 'stats' | 'testimonials' | 'faqs'>(key: K, content: LandingContent, index: number, value: LandingContent[K][number], onChange: (content: LandingContent) => void) { const list = [...content[key]] as LandingContent[K]; list[index] = value as never; onChange({ ...content, [key]: list }); }
function updateReason(content: LandingContent, index: number, value: LandingContent['whySection']['reasons'][number], onChange: (content: LandingContent) => void) { const reasons = [...content.whySection.reasons]; reasons[index] = value; onChange({ ...content, whySection: { ...content.whySection, reasons } }); }
function ArrayEditor({ heading, description, addLabel, onAdd, children }: { heading: string; description: string; addLabel: string; onAdd: () => void; children: ReactNode }) { return <div className="landing-editor"><SectionHeading number="•" title={heading} description={description} />{children}<Button type="button" variant="outline" onClick={onAdd} className="landing-editor__add"><Plus /> {addLabel}</Button></div>; }
function ItemCard({ index, label, onDelete, children }: { index: number; label: string; onDelete?: () => void; children: ReactNode }) { const tr = useUiCopy(adminLandingMessages); return <article className="landing-editor__item"><header><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong>{onDelete && <button type="button" onClick={onDelete} aria-label={tr("Delete {label}", { label })}><Trash2 /></button>}</header>{children}</article>; }

function LandingPreview({ content }: { content: LandingContent }) {
  const tr = useUiCopy(adminLandingMessages); return <aside className="landing-console__preview" aria-label={tr("Live landing page preview")}><header><div><Monitor /><span>{tr("Live preview")}</span></div><Smartphone /></header><div className="landing-console__browser"><div><i /><i /><i /><span>twobeone.app</span></div><section><span>{content.hero.badge}</span><h2>{content.hero.title}<em>{content.hero.subtitle}</em></h2><p>{content.hero.description}</p><button type="button" tabIndex={-1}>{content.cta.buttonText}</button><blockquote>{content.hero.scripture.text}<small>{content.hero.scripture.reference}</small></blockquote><div className="landing-console__proof"><span><Users /> {tr('{count} couples', { count: content.hero.socialProof.couplesCount })}</span><span><Star /> {tr('{rating} rating', { rating: content.hero.socialProof.rating.toFixed(1) })}</span></div></section><div className="landing-console__preview-features">{content.features.slice(0, 3).map((feature, index) => <article key={index}><i>{index === 0 ? <BookOpen /> : index === 1 ? <MessageSquare /> : <Heart />}</i><strong>{feature.title}</strong><p>{feature.description}</p></article>)}</div><div className="landing-console__preview-stats">{content.stats.slice(0, 4).map((stat, index) => <span key={index}><b>{stat.value}</b>{stat.label}</span>)}</div><footer><Heart /><strong>{content.cta.title}</strong><p>{content.cta.description}</p></footer></div></aside>; }
