import type { ReactNode } from 'react';
import { BookOpen, Check, ChevronRight, Eye, FileText, Heart, Image, LayoutTemplate, Mail, MessageSquare, Monitor, Plus, RefreshCw, RotateCcw, Save, Smartphone, Sparkles, Star, Trash2, TrendingUp, Users } from 'lucide-react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Label } from '../../ui/label';
import { Textarea } from '../../ui/textarea';
import type { LandingContent, NewsletterSubscriber } from '../LandingPageManager';

type Section = 'hero' | 'features' | 'why' | 'stats' | 'testimonials' | 'faqs' | 'cta';
interface Props {
  content: LandingContent; subscribers: NewsletterSubscriber[]; subscribersCount: number;
  isLoading: boolean; isSaving: boolean; isDirty: boolean; activeView: 'content' | 'media' | 'subscribers';
  activeSection: Section; media: ReactNode; onViewChange: (view: Props['activeView']) => void;
  onSectionChange: (section: Section) => void; onContentChange: (content: LandingContent) => void;
  onSave: () => void; onReload: () => void; onReset: () => void;
}

const sectionMeta: Array<{ id: Section; label: string; icon: typeof Heart }> = [
  { id: 'hero', label: 'Hero message', icon: Heart }, { id: 'features', label: 'Feature grid', icon: Sparkles },
  { id: 'why', label: 'Why TwoBeOne', icon: BookOpen }, { id: 'stats', label: 'Social proof', icon: TrendingUp },
  { id: 'testimonials', label: 'Testimonials', icon: Star }, { id: 'faqs', label: 'FAQs', icon: MessageSquare },
  { id: 'cta', label: 'Final CTA', icon: ChevronRight },
];
const icons = ['BookOpen', 'MessageSquare', 'Heart', 'Users', 'Sparkles', 'TrendingUp', 'Shield', 'Zap', 'Globe', 'Star'];
const colors = ['from-warning-500 to-warning-500', 'from-sky-500 to-sky-600', 'from-primary-500 to-primary-600', 'from-primary-500 to-sky-500', 'from-success-500 to-success-700'];

export function LandingPageWorkspace(props: Props) {
  const { content, subscribers, subscribersCount, isLoading, isSaving, isDirty, activeView, activeSection,
    media, onViewChange, onSectionChange, onContentChange, onSave, onReload, onReset } = props;
  const totalBlocks = content.features.length + content.stats.length + content.testimonials.length + content.faqs.length;
  return <main className="landing-console">
    <header className="landing-console__hero"><div><span className="landing-console__eyebrow"><Sparkles /> Publishing studio</span><h1>Landing Page</h1><p>Craft the first impression, preview the story, and publish updates from one focused workspace.</p></div><div className="landing-console__hero-actions"><span className={isDirty ? 'landing-console__state landing-console__state--dirty' : 'landing-console__state'}>{isDirty ? <><i /> Unsaved changes</> : <><Check /> All changes saved</>}</span><div><Button variant="outline" onClick={onReload} disabled={isLoading} aria-label="Reload landing page content"><RefreshCw className={isLoading ? 'landing-console__spin' : ''} /> Reload</Button><Button onClick={onSave} disabled={isSaving || !isDirty} className="landing-console__primary" aria-label="Save landing page changes">{isSaving ? <RefreshCw className="landing-console__spin" /> : <Save />} {isSaving ? 'Saving…' : 'Save changes'}</Button></div></div></header>

    <section className="landing-console__metrics" aria-label="Landing page summary"><article><span><LayoutTemplate /></span><div><strong>7</strong><small>Page sections</small></div></article><article><span><FileText /></span><div><strong>{totalBlocks}</strong><small>Content blocks</small></div></article><article><span><Star /></span><div><strong>{content.testimonials.length}</strong><small>Testimonials</small></div></article><article><span><Mail /></span><div><strong>{subscribersCount}</strong><small>Subscribers</small></div></article></section>

    <nav className="landing-console__views" aria-label="Landing page workspace"><button type="button" data-active={activeView === 'content' || undefined} onClick={() => onViewChange('content')} aria-pressed={activeView === 'content'}><LayoutTemplate /> Content studio</button><button type="button" data-active={activeView === 'media' || undefined} onClick={() => onViewChange('media')} aria-pressed={activeView === 'media'}><Image /> Media library</button><button type="button" data-active={activeView === 'subscribers' || undefined} onClick={() => onViewChange('subscribers')} aria-pressed={activeView === 'subscribers'}><Mail /> Subscribers <span>{subscribersCount}</span></button></nav>

    {activeView === 'content' && <section className="landing-console__workspace"><aside className="landing-console__sections" aria-label="Landing page sections"><div><span>Page structure</span><small>{totalBlocks} editable blocks</small></div>{sectionMeta.map(({ id, label, icon: Icon }, index) => <button type="button" key={id} data-active={activeSection === id || undefined} onClick={() => onSectionChange(id)} aria-current={activeSection === id ? 'step' : undefined}><span>{String(index + 1).padStart(2, '0')}</span><Icon /><div><strong>{label}</strong><small>{sectionCount(id, content)}</small></div><ChevronRight /></button>)}<button className="landing-console__reset" type="button" onClick={onReset}><RotateCcw /> Reset default content</button></aside><div className="landing-console__editor"><Editor section={activeSection} content={content} onChange={onContentChange} /></div><LandingPreview content={content} /></section>}
    {activeView === 'media' && <section className="landing-console__panel"><div className="landing-console__panel-title"><div><Image /><span><h2>Media library</h2><p>Manage the screenshots used to showcase the app.</p></span></div></div>{media}</section>}
    {activeView === 'subscribers' && <section className="landing-console__panel"><div className="landing-console__panel-title"><div><Mail /><span><h2>Newsletter audience</h2><p>People who asked to hear about product updates and relationship resources.</p></span></div><b>{subscribersCount} total</b></div><div className="landing-console__subscribers">{subscribers.map((subscriber, index) => <article key={`${subscriber.email}-${index}`}><span>{subscriber.email.slice(0, 1).toUpperCase()}</span><div><strong>{subscriber.email}</strong><small>Subscribed {new Date(subscriber.subscribedAt).toLocaleDateString()}</small></div><i>{subscriber.status || 'active'}</i></article>)}{!subscribers.length && <div className="landing-console__empty"><Mail /><h2>No subscribers yet</h2><p>New newsletter signups will appear here automatically.</p></div>}</div></section>}
  </main>;
}

function sectionCount(section: Section, content: LandingContent) { if (section === 'features') return `${content.features.length} feature cards`; if (section === 'stats') return `${content.stats.length} statistics`; if (section === 'testimonials') return `${content.testimonials.length} stories`; if (section === 'faqs') return `${content.faqs.length} questions`; if (section === 'why') return `${content.whySection.reasons.length} reasons`; return section === 'hero' ? 'Headline & Scripture' : 'Conversion message'; }
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="landing-editor__field"><Label>{label}</Label>{children}{hint && <small>{hint}</small>}</label>; }
function SectionHeading({ number, title, description }: { number: string; title: string; description: string }) { return <div className="landing-editor__heading"><span>{number}</span><div><h2>{title}</h2><p>{description}</p></div></div>; }

function Editor({ section, content, onChange }: { section: Section; content: LandingContent; onChange: (content: LandingContent) => void }) {
  const update = <K extends keyof LandingContent>(key: K, value: LandingContent[K]) => onChange({ ...content, [key]: value });
  if (section === 'hero') return <div className="landing-editor"><SectionHeading number="01" title="Hero message" description="Make the value clear within the first few seconds." /><Field label="Eyebrow badge"><Input value={content.hero.badge} onChange={(e) => update('hero', { ...content.hero, badge: e.target.value })} /></Field><Field label="Main headline" hint={`${content.hero.title.length} characters`}><Input value={content.hero.title} onChange={(e) => update('hero', { ...content.hero, title: e.target.value })} /></Field><Field label="Highlighted headline"><Input value={content.hero.subtitle} onChange={(e) => update('hero', { ...content.hero, subtitle: e.target.value })} /></Field><Field label="Supporting description" hint={`${content.hero.description.length} characters`}><Textarea rows={4} value={content.hero.description} onChange={(e) => update('hero', { ...content.hero, description: e.target.value })} /></Field><div className="landing-editor__grid"><Field label="Scripture"><Textarea rows={4} value={content.hero.scripture.text} onChange={(e) => update('hero', { ...content.hero, scripture: { ...content.hero.scripture, text: e.target.value } })} /></Field><div><Field label="Reference"><Input value={content.hero.scripture.reference} onChange={(e) => update('hero', { ...content.hero, scripture: { ...content.hero.scripture, reference: e.target.value } })} /></Field><div className="landing-editor__grid"><Field label="Couples count"><Input value={content.hero.socialProof.couplesCount} onChange={(e) => update('hero', { ...content.hero, socialProof: { ...content.hero.socialProof, couplesCount: e.target.value } })} /></Field><Field label="Rating"><Input type="number" min="1" max="5" value={content.hero.socialProof.rating} onChange={(e) => update('hero', { ...content.hero, socialProof: { ...content.hero.socialProof, rating: Number(e.target.value) } })} /></Field></div></div></div></div>;
  if (section === 'features') return <ArrayEditor heading="Feature grid" description="Show the core experiences couples receive." addLabel="Add feature" onAdd={() => update('features', [...content.features, { title: 'New feature', description: 'Describe the value for couples.', icon: 'Heart', color: colors[0] }])}>{content.features.map((item, index) => <ItemCard key={index} index={index} label={item.title || 'Untitled feature'} onDelete={() => update('features', content.features.filter((_, i) => i !== index))}><Field label="Title"><Input value={item.title} onChange={(e) => updateAt('features', content, index, { ...item, title: e.target.value }, onChange)} /></Field><Field label="Description"><Textarea rows={3} value={item.description} onChange={(e) => updateAt('features', content, index, { ...item, description: e.target.value }, onChange)} /></Field><div className="landing-editor__grid"><Field label="Icon"><select value={item.icon} onChange={(e) => updateAt('features', content, index, { ...item, icon: e.target.value }, onChange)}>{icons.map((icon) => <option key={icon}>{icon}</option>)}</select></Field><Field label="Theme"><select value={item.color} onChange={(e) => updateAt('features', content, index, { ...item, color: e.target.value }, onChange)}>{colors.map((color) => <option key={color}>{color.replaceAll('-', ' ')}</option>)}</select></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'why') return <div className="landing-editor"><SectionHeading number="03" title="Why TwoBeOne" description="Explain the deeper purpose and trust promise." /><Field label="Badge"><Input value={content.whySection.badge} onChange={(e) => update('whySection', { ...content.whySection, badge: e.target.value })} /></Field><Field label="Title"><Input value={content.whySection.title} onChange={(e) => update('whySection', { ...content.whySection, title: e.target.value })} /></Field><Field label="Description"><Textarea rows={4} value={content.whySection.description} onChange={(e) => update('whySection', { ...content.whySection, description: e.target.value })} /></Field>{content.whySection.reasons.map((reason, index) => <ItemCard key={index} index={index} label={reason.title}><div className="landing-editor__grid"><Field label="Icon"><select value={reason.icon} onChange={(e) => updateReason(content, index, { ...reason, icon: e.target.value }, onChange)}>{icons.map((icon) => <option key={icon}>{icon}</option>)}</select></Field><Field label="Title"><Input value={reason.title} onChange={(e) => updateReason(content, index, { ...reason, title: e.target.value }, onChange)} /></Field></div><Field label="Description"><Textarea rows={2} value={reason.description} onChange={(e) => updateReason(content, index, { ...reason, description: e.target.value }, onChange)} /></Field></ItemCard>)}</div>;
  if (section === 'stats') return <ArrayEditor heading="Social proof" description="Keep proof points concise and credible." addLabel="Add statistic" onAdd={() => update('stats', [...content.stats, { label: 'New metric', value: '0', gradient: 'from-primary-50 to-primary-50' }])}>{content.stats.map((item, index) => <ItemCard key={index} index={index} label={item.label} onDelete={() => update('stats', content.stats.filter((_, i) => i !== index))}><div className="landing-editor__grid"><Field label="Value"><Input value={item.value} onChange={(e) => updateAt('stats', content, index, { ...item, value: e.target.value }, onChange)} /></Field><Field label="Label"><Input value={item.label} onChange={(e) => updateAt('stats', content, index, { ...item, label: e.target.value }, onChange)} /></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'testimonials') return <ArrayEditor heading="Testimonials" description="Share authentic stories from couples." addLabel="Add testimonial" onAdd={() => update('testimonials', [...content.testimonials, { name: 'New couple', location: 'City', image: '💑', quote: 'Share their story here.', rating: 5, married: '1 year' }])}>{content.testimonials.map((item, index) => <ItemCard key={index} index={index} label={item.name} onDelete={() => update('testimonials', content.testimonials.filter((_, i) => i !== index))}><div className="landing-editor__grid"><Field label="Couple"><Input value={item.name} onChange={(e) => updateAt('testimonials', content, index, { ...item, name: e.target.value }, onChange)} /></Field><Field label="Location"><Input value={item.location} onChange={(e) => updateAt('testimonials', content, index, { ...item, location: e.target.value }, onChange)} /></Field></div><Field label="Quote"><Textarea rows={4} value={item.quote} onChange={(e) => updateAt('testimonials', content, index, { ...item, quote: e.target.value }, onChange)} /></Field><div className="landing-editor__grid landing-editor__grid--three"><Field label="Avatar"><Input value={item.image} onChange={(e) => updateAt('testimonials', content, index, { ...item, image: e.target.value }, onChange)} /></Field><Field label="Rating"><Input type="number" min="1" max="5" value={item.rating} onChange={(e) => updateAt('testimonials', content, index, { ...item, rating: Number(e.target.value) }, onChange)} /></Field><Field label="Together"><Input value={item.married} onChange={(e) => updateAt('testimonials', content, index, { ...item, married: e.target.value }, onChange)} /></Field></div></ItemCard>)}</ArrayEditor>;
  if (section === 'faqs') return <ArrayEditor heading="Frequently asked questions" description="Resolve hesitation before a visitor leaves." addLabel="Add FAQ" onAdd={() => update('faqs', [...content.faqs, { question: 'New question?', answer: 'Add a clear answer.' }])}>{content.faqs.map((item, index) => <ItemCard key={index} index={index} label={item.question} onDelete={() => update('faqs', content.faqs.filter((_, i) => i !== index))}><Field label="Question"><Input value={item.question} onChange={(e) => updateAt('faqs', content, index, { ...item, question: e.target.value }, onChange)} /></Field><Field label="Answer"><Textarea rows={3} value={item.answer} onChange={(e) => updateAt('faqs', content, index, { ...item, answer: e.target.value }, onChange)} /></Field></ItemCard>)}</ArrayEditor>;
  return <div className="landing-editor"><SectionHeading number="07" title="Final call to action" description="End with one confident, low-friction next step." /><Field label="Title"><Input value={content.cta.title} onChange={(e) => update('cta', { ...content.cta, title: e.target.value })} /></Field><Field label="Description"><Textarea rows={3} value={content.cta.description} onChange={(e) => update('cta', { ...content.cta, description: e.target.value })} /></Field><div className="landing-editor__grid"><Field label="Newsletter label"><Input value={content.cta.newsletterLabel} onChange={(e) => update('cta', { ...content.cta, newsletterLabel: e.target.value })} /></Field><Field label="Button text"><Input value={content.cta.buttonText} onChange={(e) => update('cta', { ...content.cta, buttonText: e.target.value })} /></Field></div><Field label="Reassurance text"><Input value={content.cta.footer} onChange={(e) => update('cta', { ...content.cta, footer: e.target.value })} /></Field></div>;
}

function updateAt<K extends 'features' | 'stats' | 'testimonials' | 'faqs'>(key: K, content: LandingContent, index: number, value: LandingContent[K][number], onChange: (content: LandingContent) => void) { const list = [...content[key]] as LandingContent[K]; list[index] = value as never; onChange({ ...content, [key]: list }); }
function updateReason(content: LandingContent, index: number, value: LandingContent['whySection']['reasons'][number], onChange: (content: LandingContent) => void) { const reasons = [...content.whySection.reasons]; reasons[index] = value; onChange({ ...content, whySection: { ...content.whySection, reasons } }); }
function ArrayEditor({ heading, description, addLabel, onAdd, children }: { heading: string; description: string; addLabel: string; onAdd: () => void; children: ReactNode }) { return <div className="landing-editor"><SectionHeading number="•" title={heading} description={description} />{children}<Button type="button" variant="outline" onClick={onAdd} className="landing-editor__add"><Plus /> {addLabel}</Button></div>; }
function ItemCard({ index, label, onDelete, children }: { index: number; label: string; onDelete?: () => void; children: ReactNode }) { return <article className="landing-editor__item"><header><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong>{onDelete && <button type="button" onClick={onDelete} aria-label={`Delete ${label}`}><Trash2 /></button>}</header>{children}</article>; }

function LandingPreview({ content }: { content: LandingContent }) { return <aside className="landing-console__preview" aria-label="Live landing page preview"><header><div><Monitor /><span>Live preview</span></div><Smartphone /></header><div className="landing-console__browser"><div><i /><i /><i /><span>twobeone.app</span></div><section><span>{content.hero.badge}</span><h2>{content.hero.title}<em>{content.hero.subtitle}</em></h2><p>{content.hero.description}</p><button type="button" tabIndex={-1}>{content.cta.buttonText}</button><blockquote>{content.hero.scripture.text}<small>{content.hero.scripture.reference}</small></blockquote><div className="landing-console__proof"><span><Users /> {content.hero.socialProof.couplesCount} couples</span><span><Star /> {content.hero.socialProof.rating}.0 rating</span></div></section><div className="landing-console__preview-features">{content.features.slice(0, 3).map((feature, index) => <article key={index}><i>{index === 0 ? <BookOpen /> : index === 1 ? <MessageSquare /> : <Heart />}</i><strong>{feature.title}</strong><p>{feature.description}</p></article>)}</div><div className="landing-console__preview-stats">{content.stats.slice(0, 4).map((stat, index) => <span key={index}><b>{stat.value}</b>{stat.label}</span>)}</div><footer><Heart /><strong>{content.cta.title}</strong><p>{content.cta.description}</p></footer></div></aside>; }
